105/preprocessing
Cyberjusticelab/JusticeAI pull request #121
Opened 2017-11-01 07:26 UTC by Samuel-Campbell

2017-11-01 07:36 UTC, Samuel-Campbell commented on src/nlp_service/preprocessing/French/NerTraining.py
> +    def __annotate_raw_text(self, text, tuple_list):
Ill refactor this later if we use it seriously.

2017-11-01 13:39 UTC, arekmano requested changes
remove .pyc files from PR. add a rule to .gitignore

2017-11-01 13:39 UTC, arekmano commented
Add a description to your PR please

2017-11-01 17:20 UTC, Taimoorrana1 commented on src/ml_service/preprocessing/French/french_data/5.txt
> +fr-5
Not sure if we should be uploading this file

2017-11-01 17:22 UTC, Samuel-Campbell commented on src/ml_service/preprocessing/French/french_data/5.txt
> +fr-5
i will remove it. I'm downloading arek's word_vector model and i will retrain my stuff with it then only upload my Matrix as a .bin

2017-11-02 13:43 UTC, Samuel-Campbell commented
Don't merge code yet. I'll change 1 last thing when i get home

2017-11-02 15:51 UTC, Taimoorrana1 commented on src/nlp_service/services/is_student_classifier_test.py
> +        'is_student'] == 'true'
it's better that we find the issue instead of changing this test

2017-11-02 17:08 UTC, Samuel-Campbell commented on src/nlp_service/services/is_student_classifier_test.py
> +        'is_student'] == 'true'
yes this is what i'm going to change. I realized that I accidently removed all the 'stem' methods from the project when i did a find and replace. This is why this classifier fails

2017-11-02 17:45 UTC, Taimoorrana1 commented
I noticed that there a few __init__.py files that are empty... what are those? for example in  `src/ml_service/WordVectors/__init__.py`

2017-11-02 17:49 UTC, Vynny commented
@Taimoorrana1 empty __init__.py files in python just indicate that that folder is a module.

2017-11-02 18:02 UTC, Samuel-Campbell commented
Yes as Vynny says you need __init__.py in order to tell the interpreter that the folder is a module. Without __init__.py then you can't traverse the subdirectory.

2017-11-03 03:11 UTC, arekmano approved these changes
Looks good, minus gensim duplicate requirement

2017-11-03 05:41 UTC, merged