105/hdbscan
Cyberjusticelab/JusticeAI pull request #132
Opened 2017-11-04 21:15 UTC by Samuel-Campbell

- New file structure
- Refactored code to match file structure (imports)
- Implemented HDBSCAN algorithm

2017-11-04 21:20 UTC, arekmano requested changes

2017-11-04 21:20 UTC, arekmano commented on src/ml_service/GlobalVariables/GlobalVariable.py
> +        __rel_path = r'MLModels/ner_model.pickle'
where is this pickle file getting stored?

2017-11-04 21:20 UTC, arekmano commented on src/ml_service/.gitignore
> +/feature_extraction/Preprocessing/train.py
why are these in .gitignore?

2017-11-04 21:21 UTC, Samuel-Campbell commented on src/ml_service/GlobalVariables/GlobalVariable.py
> +        __rel_path = r'MLModels/ner_model.pickle'
relative path. 2 directories up in a new folder called MLModels

2017-11-04 21:21 UTC, Samuel-Campbell commented on src/ml_service/.gitignore
> +/feature_extraction/Preprocessing/train.py
because it;s sample code i'm personally using to test stuff

2017-11-05 04:19 UTC, arekmano reviewed
.

2017-11-05 04:19 UTC, arekmano commented on src/ml_service/feature_extraction/Preprocessing/Sam_Parser/Model.py
>                  word_list[i] = 'propriétaire'
Maintaining a list like this might suck

2017-11-05 04:19 UTC, arekmano commented on src/ml_service/feature_extraction/Preprocessing/Sam_Parser/Vectorize.py
> +        self.word_vectors.save_word2vec_format(file, binary=True)
Are you modifying the model?

2017-11-05 19:27 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/Preprocessing/Sam_Parser/Vectorize.py
> +        self.word_vectors.save_word2vec_format(file, binary=True)
no. This is for custom model i was using which i sitll need to evaluate the metric for

2017-11-05 19:27 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/Preprocessing/Sam_Parser/Model.py
>                  word_list[i] = 'propriétaire'
yeah i'm trying to work around it

2017-11-05 23:25 UTC, Samuel-Campbell commented
@Taimoorrana1  doesn't really matter. As long as the vector is the same

2017-11-06 03:31 UTC, arekmano commented
https://fr.wiktionary.org/wiki/locatrice it is a word

2017-11-06 18:26 UTC, arekmano approved these changes
:+1:

2017-11-06 18:27 UTC, merged