[#75] Replaces NLP system with Rasa
Cyberjusticelab/JusticeAI pull request #148
Opened 2017-11-09 22:50 UTC by Vynny

[#75]

*This is a work in progress*

- [ ] Imports rasa NLU into nlp service
- [ ] Adds training data for problem classification and fact extraction
- [ ] Adds fact extraction & problem classification via rasa NLU engine
- [ ] Defines new HTTP interfaces between backend -> nlp
- [ ] Changes db models to new format (now with FactEntities)
- [ ] Changes application data flow to agreed upon format (backend <-> nlp *<->ml*)

2017-11-09 23:06 UTC, arekmano submitted a review, later dismissed

2017-11-09 23:06 UTC, arekmano commented on src/nlp_service/app.py
> +training_data = load_data('rasa/data/Problem_identifier.json')  # Where to fish the data it is being trained
This training should be done in init.py or equivalent. Else, initializing will take forever

2017-11-09 23:06 UTC, arekmano commented on src/nlp_service/rasa/app_test.py
> +trainer.train(training_data)
Has potential to break travis when training data becomes sufficiently large

2017-11-09 23:06 UTC, arekmano commented on src/nlp_service/rasa/data/data.json
> +  "rasa_nlu_data": {
sample data does not belong in our project

2017-11-09 23:42 UTC, mihaiqc commented on src/nlp_service/app.py
> +training_data = load_data('rasa/data/Problem_identifier.json')  # Where to fish the data it is being trained
We will be changing a lot of the structure shortly.

2017-11-09 23:43 UTC, mihaiqc commented on src/nlp_service/rasa/data/data.json
> +  "rasa_nlu_data": {
This will also be removed.

2017-11-10 05:15 UTC, arekmano commented on src/backend_service/app.py
> +#db = database.connect(app, 'postgres', 'postgres', 'postgres', host='127.0.0.1')
no commented code

2017-11-10 07:51 UTC, Samuel-Campbell commented on src/postgresql_db/models.py
> +        self.file_request = file_request
not a big deal for this one but consider that 'file_request' is declared static in this scope and using the keyword self. you are creating a separate instance of file_request.
I don't know if it's intentional

2017-11-10 07:51 UTC, Samuel-Campbell commented on src/postgresql_db/models.py
> +        self.document_type = document_type
same as previous comment

2017-11-10 07:51 UTC, Samuel-Campbell commented on src/nlp_service/rasa/rasa_classifier.py
> +class RasaClassifier(object):
why are you inheriting object?

2017-11-10 07:51 UTC, Samuel-Campbell commented on src/nlp_service/rasa/app_test.py
> +#  'entities': [{'value': 'faggot', 'entity': 'person', 'start': 3, 'end': 9, 'extractor': 'ner_crf'},
NICE VALUE! 👍

2017-11-10 08:08 UTC, Vynny commented on src/nlp_service/rasa/rasa_classifier.py
> +class RasaClassifier(object):
My bad, forgot it was implicit.

2017-11-10 08:10 UTC, Vynny commented on src/postgresql_db/models.py
> +        self.file_request = file_request
Yeah it's creating a new file request. I guess it could be simplified to self.file_request = FileRequest...

2017-11-11 15:06 UTC, arekmano requested changes

2017-11-11 15:06 UTC, arekmano commented on src/nlp_service/controllers/nlpController.py
> +# from postgresql_db.models import *
remove?

2017-11-11 15:06 UTC, arekmano commented on src/nlp_service/controllers/nlpController.py
> +        # db.session.commit()
remove

2017-11-11 15:06 UTC, arekmano commented on src/nlp_service/controllers/nlpController.py
> +def __is_answer_sufficient(classify_dict):
wouldn't this belong in the RasaClassifier?

2017-11-11 15:06 UTC, arekmano commented on src/nlp_service/feature_extraction/Models/compliment.py
>  from feature_extraction.Models import Abstract_Model
Are we still using these files in our classification?

2017-11-11 15:06 UTC, arekmano commented on src/nlp_service/gram_classify/introduction_parser.py
> +from models.classifier.introduction import IntroductionOutput
we can rm this file

2017-11-11 20:23 UTC, arekmano commented on .gitignore
>  src/__pycache__/
you can remove this. same as below

2017-11-11 20:36 UTC, Taimoorrana1 commented on src/nlp_service/controllers/nlpController.py
> +        # db.session.commit()
👍

2017-11-11 20:44 UTC, Taimoorrana1 commented on src/nlp_service/services/mlService.py
> +# Returns first fact to ask
Please use docstrings

2017-11-11 20:47 UTC, Taimoorrana1 commented on src/postgresql_db/models.py
> +    name = db.Column(db.String(50), nullable=False)
Consider assigning string length to a variable since it’s being used a few times in this Class

2017-11-12 01:23 UTC, mihaiqc commented on src/nlp_service/services/mlService.py
> +# Returns first fact to ask
Noted

2017-11-12 04:04 UTC, Vynny commented
Everything is working but RasaClassifier is causing the docker container to run out of memory.
Investigating this currently.

2017-11-12 19:23 UTC, Samuel-Campbell commented on src/nlp_service/feature_extraction/Models/compliment.py
>  from feature_extraction.Models import Abstract_Model
no. please delete this

2017-11-12 19:23 UTC, Samuel-Campbell commented on src/nlp_service/feature_extraction/Models/proposition.py
> -from feature_extraction.Models import clause as c, compliment as cmp, predicate as p
delete this file

2017-11-12 19:23 UTC, Samuel-Campbell commented on src/nlp_service/feature_extraction/Models/proposition.py
> +from feature_extraction.Models import compliment as cmp, predicate as p
delete this file

2017-11-12 19:23 UTC, Samuel-Campbell commented on src/nlp_service/feature_extraction/fact_extraction.py
delete file

2017-11-12 19:23 UTC, Samuel-Campbell commented on src/nlp_service/rasa/app_test.py
> +import os
missing assertions

2017-11-12 19:37 UTC, Vynny commented on src/nlp_service/feature_extraction/fact_extraction.py
We'll just delete the entire module. If we need it later, we'll fish it out.

2017-11-12 20:34 UTC, arekmano commented on src/backend_service/controllers/conversationController.py
>  def __get_conversation(conversation_id):
we need some documentation on this method. The if/elif statements need explaining

2017-11-12 20:35 UTC, arekmano commented on src/nlp_service/gram_classify/classifiers/has_lease_expired_classifier.py
>  class HasLeaseExpiredClassifier(GramClassifier):
are we still using these classifiers?

2017-11-12 22:50 UTC, Vynny commented on src/backend_service/controllers/conversationController.py
>  def __get_conversation(conversation_id):
__get_conversation()?
I don't think it needs documentation. If the conversation exists it's returned, else it aborts with a 404.

2017-11-12 23:05 UTC, Taimoorrana1 commented on src/backend_service/app_test.py
>  ################
Please use docstrings

2017-11-12 23:06 UTC, Vynny commented on src/backend_service/app_test.py
>  ################
That isn't documenting anything, it's just marking sections in the test file since its not using unittest at the moment.

2017-11-12 23:15 UTC, Taimoorrana1 commented on src/nlp_service/app.py
> +def submit_message():
what does this return?

2017-11-12 23:20 UTC, Taimoorrana1 commented on src/nlp_service/controllers/nlpController.py
> +        print("Confidence: {}%".format(round(determined_problem_category['confidence'], 3) * 100))
are these being printed for debugging purposes?

2017-11-12 23:21 UTC, Taimoorrana1 commented on src/nlp_service/rasa/rasa_classifier.py
> +            0.5 * (confidence_contender + confidence_top))
why 0.5? will this value ever be changed in the future?

2017-11-12 23:22 UTC, Vynny commented on src/nlp_service/app.py
> +def submit_message():
The documentation for the return is in nlpController.
These are simply the HTTP routes, all the important functionality is in nlpController. This is done the same way in backend_service so that app.py is not polluted.

2017-11-12 23:23 UTC, Taimoorrana1 commented on src/postgresql_db/models.py
>      name = db.Column(db.String(50), nullable=False)
please assign these values to variables

2017-11-12 23:23 UTC, Vynny commented on src/nlp_service/controllers/nlpController.py
> +        print("Confidence: {}%".format(round(determined_problem_category['confidence'], 3) * 100))
These would go into logs, however since we don't have logging functionality at the moment they're just being printed out to the console.

2017-11-12 23:24 UTC, Vynny commented on src/nlp_service/rasa/rasa_classifier.py
> +            0.5 * (confidence_contender + confidence_top))
It's part of the formula:
Percent difference of x and y
=
abs(x-y) / (1/2 * (x + y))

2017-11-12 23:24 UTC, TaimoorRana requested changes
See the comments I left

2017-11-12 23:28 UTC, Taimoorrana1 commented on src/nlp_service/controllers/nlpController.py
> +        print("Confidence: {}%".format(round(determined_problem_category['confidence'], 3) * 100))
there is a logger in /src/ml_service/outputs/output.py maybe you can use that

2017-11-12 23:34 UTC, mihaiqc commented on src/backend_service/controllers/conversationController.py
>  def __get_conversation(conversation_id):
Documentation for a getter?

2017-11-13 00:14 UTC, mihaiqc commented on src/postgresql_db/models.py
> +    name = db.Column(db.String(50), nullable=False)
Why?

2017-11-13 00:21 UTC, mihaiqc commented on src/nlp_service/controllers/nlpController.py
> +        print("Confidence: {}%".format(round(determined_problem_category['confidence'], 3) * 100))
Print allows us to go much faster during development as quick changes and tweaks are necessary during such refactoring measures taken during this PR.

Maybe in the future output.py will be used, as of now, it was not necessary.

2017-11-13 00:48 UTC, mihaiqc commented on src/postgresql_db/models.py
>      name = db.Column(db.String(50), nullable=False)
This is unnecessary and even cumbersome to us.

2017-11-13 00:51 UTC, Vynny commented on src/nlp_service/controllers/nlpController.py
> +        print("Confidence: {}%".format(round(determined_problem_category['confidence'], 3) * 100))
We shouldn't have an ad-hoc logger.
We should eventually add an actual logging solution with log levels. 
We can discuss it in the next meeting, but we'll remove the prints.

2017-11-13 01:44 UTC, Taimoorrana1 commented on src/postgresql_db/models.py
>      name = db.Column(db.String(50), nullable=False)
why is that?

2017-11-13 01:48 UTC, Taimoorrana1 commented on src/postgresql_db/models.py
> +    name = db.Column(db.String(50), nullable=False)
I find it's better because if you need to change 50 to 60, then you have to change that in several places in this class. It's better if we had to only change it in 1 location.

2017-11-13 02:02 UTC, mihaiqc commented on src/backend_service/controllers/conversationController.py
>  def __get_conversation(conversation_id):
Fixed.

2017-11-13 02:02 UTC, mihaiqc commented on src/backend_service/app_test.py
>  ################
Added Documentation for tests.

2017-11-13 02:03 UTC, mihaiqc commented on src/nlp_service/app.py
> +def submit_message():
Added documentation for routing mechanism

2017-11-13 02:38 UTC, mihaiqc commented on src/postgresql_db/models.py
> +    name = db.Column(db.String(50), nullable=False)
This is 3-4 times less intuitive and more confusing than just delimiting the size of the column with a [simple number](http://flask-sqlalchemy.pocoo.org/2.3/models/).

2017-11-13 02:39 UTC, Samuel-Campbell approved these changes
Guys it looks fine. we can refactor docstring or wtv later. it's not important

2017-11-13 02:41 UTC, ghost approved these changes

2017-11-13 02:42 UTC, TaimoorRana approved these changes

2017-11-13 04:10 UTC, arekmano commented on src/backend_service/app.py
> +from controllers import conversationController, legalController
use snake_scase. keep style consistent

2017-11-13 04:12 UTC, arekmano commented on src/nlp_service/controllers/nlpController.py
> +rasaClassifier.train(force_train=True)
this will slow boot time significantly as we expand RASA (non-blocking comment ...for now)

2017-11-13 04:12 UTC, arekmano commented on src/nlp_service/controllers/nlpController.py
> +        claim_category=conversation.claim_category.value.lower().replace("_", " "),
why are we doing this replace magic?

2017-11-13 04:22 UTC, arekmano commented on src/nlp_service/rasa/rasa_classifier.py
> +            0.5 * (confidence_contender + confidence_top))
This is a bug waiting to happen IMO.

This works well when there are only 2 intents that matter. Consider 0.3 0.2 0.1 0.1 etc... This percent difference will accept 0.3 as a high enough confidence, Whereas it is only 30% sure that this is the correct category, and it should cause reprompt since the classifier is not sure.

This is a borderline blocker for me. This heuristic cannot be the best way of doing things, especially when thresholding can be done. Either put a TODO comment here to address in the future, when we classify multiple intents or we find a solution before PR goes through

2017-11-13 04:26 UTC, arekmano requested changes
See Percent difference comment. After that fix, you can dismiss my review/ping me so I approve it.

2017-11-13 04:40 UTC, Vynny commented on src/nlp_service/controllers/nlpController.py
> +rasaClassifier.train(force_train=True)
Yeah I definitely need to fix this. I set it to true because even without force train, rasa seems to take forever loading pre trained data. It takes 1 second less to load pre trained models than to just retrain, so I might be missing something from the docs.

I'll add a fix for this in another PR. Right now it's fast enough so that it doesn't had adverse effects.

2017-11-13 04:41 UTC, Vynny commented on src/nlp_service/controllers/nlpController.py
> +        claim_category=conversation.claim_category.value.lower().replace("_", " "),
This could be made a bit nicer, but it's essentially taking the value of the claim category enum and removing the _.
LEASE_TERMINATION -> lease termination -> I see you're having problems with lease

2017-11-13 04:45 UTC, Vynny commented on src/nlp_service/rasa/rasa_classifier.py
> +            0.5 * (confidence_contender + confidence_top))
Good point. This needs some research put into it by the NLP team.
It was done this way because right now our facts only do have 2 intents that matter (boolean or text with 2 possible values).
I'll add a 50% threshold and a todo indicating it should be looked into thoroughly for the next iteration.

2017-11-13 04:54 UTC, arekmano approved these changes

2017-11-13 05:06 UTC, mihaiqc commented on src/nlp_service/rasa/rasa_classifier.py
> +            0.5 * (confidence_contender + confidence_top))
That's exactly the issue but with the threshold. It will be absolutely impossible to guarantee a set threshold over every model unless we specify a threshold per model due to multiple intents. Unless we all go one-by-one and polish the data to an absurd extent.

Ex: 
Model A happens to have generated 100 intents.
Model B happens to have generated 3 intents.
Threshold set at 80%.

Model B can generated Intent1, Intent2, Intent3 respectively 86, 16, 8. Which, in this case is feasible.
Model A though, 40,1, 1, 1, 1^(95).

Model A will fail even though it is clearly a lot better than the sum of the rest of the confidence percentages.

2017-11-13 05:11 UTC, arekmano requested changes

2017-11-13 05:11 UTC, arekmano commented on src/nlp_service/controllers/nlpController.py
> +        if highest_intent_confidence < minimum_intent_confidence_threshold or percent_difference < minimum_percent_difference:
should be and

2017-11-13 05:20 UTC, arekmano approved these changes

2017-11-13 05:42 UTC, merged