105/better ml
Cyberjusticelab/JusticeAI pull request #154
Opened 2017-11-11 06:28 UTC by Samuel-Campbell

- No ready for merge. Made PR so people don't duplicate stuff

2017-11-11 07:05 UTC, arekmano requested changes

2017-11-11 07:05 UTC, arekmano commented on src/ml_service/.gitignore
> +/src/ml_service/feature_extraction/preprocessing/Arek_Parser/error_words.txt
Instead of creating all these folders, we need an "output" folder. This will simplify our lives incredibly IMO

2017-11-11 07:05 UTC, arekmano commented on src/ml_service/.gitignore
> +/src/ml_service/feature_extraction/preprocessing/Arek_Parser/error_words.txt
i.e. 
/src/ml_service/outputs/{ALGORITHM_NAME}/cluster_dir
/src/ml_service/outputs/{ALGORITHM_NAME}/precedent_json

2017-11-11 07:05 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/decomposition/decompose.py
> +    Log.write("Decomposing matrix")
Is this only for plotting? Or will we reduce the number of dimensions of the inputs? If we do, then we will lose accuracy.

2017-11-11 07:05 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/main.py
> +    precedence_dict = None
👍

2017-11-11 07:05 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/dbscan/main.py
>  # -*- coding: utf-8 -*-
We should most definitely combine all the training "main"s into 1 training.py. Or else, this will become unmanageable.

then train depending on args. i.e.

python training.py all
python training.py facts
python training.py outcomes
python training.py precedents

2017-11-11 07:05 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/Arek_Parser/error_words.txt
> +santirosi
we don't need this file committed to our repo

2017-11-11 07:05 UTC, arekmano commented on src/ml_service/reporting/logger.py
> +class Log():
python logger class does this. Duplicated work. https://docs.python.org/3/howto/logging.html

2017-11-11 07:05 UTC, arekmano commented on src/ml_service/reporting/mail.py
> +    server.login("soen490.justice@gmail.com", "bustychicks")
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

2017-11-11 07:05 UTC, arekmano commented on src/ml_service/reporting/mail.py
> +    server.login("soen490.justice@gmail.com", "bustychicks")
Remove & Rebase ASAP

2017-11-11 15:33 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/clustering/decomposition/decompose.py
> +    Log.write("Decomposing matrix")
we are reducing dimensions of input with a variance of 5%. I'm just trying it

2017-11-11 16:47 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/clustering/dbscan/main.py
>  # -*- coding: utf-8 -*-
I will make it  a command line argument for which training we want

2017-11-11 17:20 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/decomposition/decompose.py
> +    Log.write("Decomposing matrix")
Using a lower dim vector solves this problem for the moment

2017-11-11 20:18 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/preprocessing/pipe/precedence_parse.py
> +# #################################################
Please remove this comment line

2017-11-11 20:21 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/preprocessing/taimor_fix_this_dir/case_test.py
> +                            "taimor_fix_this_dir/dummy_cases/sample_case1.txt")
*TaimOOr

2017-11-11 20:22 UTC, arekmano requested changes

2017-11-11 20:22 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/dbscan/dbscan_wrapper.py
> +    Log.write('Starting HDBSCAN')
but its still dbscsan

2017-11-11 20:22 UTC, arekmano commented on src/ml_service/feature_extraction/main.py
> +    process_command(sys.argv[1], sys.argv[2:])
:+1:

2017-11-11 20:22 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/pipe/save_model.py
> +    precedence_dict = parser.parse_files(Global.Precedence_Directory)
not convinced that we should keep using this preprocessing method

2017-11-11 20:27 UTC, Taimoorrana1 commented on src/ml_service/word_vectors/vectors.py
> +    Word_Vector_Size = 500
Size is being changed to 200 in another PR. Maybe change this as well

2017-11-11 20:29 UTC, Taimoorrana1 commented on src/ml_service/word_vectors/vectors.py
> +        :return: word2vec
I don’t think this is being returned anymore

2017-11-11 20:32 UTC, Taimoorrana1 commented
Nice PR 👍

2017-11-12 06:21 UTC, arekmano requested changes

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/dbscan/dbscan_wrapper.py
> +try:
why do we have src.ml_service as the default route? it doesn't work at all when i run it from ml_service directory.

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/hdbscan/hdbscan_wrapper.py
> +    from src.ml_service.global_variables.global_variable import InformationType
i really don't agree with this import method

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/ml_models/models.py
> +        :return: (matrix, list[strings], list[strings], list[[string])
what do the tuple's elements other than the first one mean?

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/outputs/output.py
> +        joblib.dump(model, file_path)
👍

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/test/feature_extraction/clustering/hdbscan/hdbscan_wrapper_test.py
> +import unittest
Tests go in the same directory as the code itself, not in a separate test folder. See vote on slack poll

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/word_vectors/vectors.py
> +    def get_stop_words():
stop_tokens is more appropriate, since we are adding punctuation

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/word_vectors/vectors.py
> +        :param word_list: String or list of tokenized words
in the future, we shouldn't have variable input args. either string or list, not both.

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/feature_extraction/main.py
> +        parse_precedence(arguments[0])
precedents**

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/precedence_parse.py
> +# -*- coding: utf-8 -*-
precedents_parse*

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/precedence_parse.py
> +    from src.ml_service.feature_extraction.preprocessing.precedence_model import PrecedenceModel, FactModel
PrecedentModel

2017-11-12 06:21 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/precedence_parse.py
> +class Precedence_Parser:
PrecedentParser. CamelCase class names to keep it consistent.

2017-11-12 06:26 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/clustering/dbscan/dbscan_wrapper.py
> +try:
it's because of unittesting

2017-11-12 06:27 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/clustering/hdbscan/hdbscan_wrapper.py
> +    from src.ml_service.global_variables.global_variable import InformationType
written right above, i don't know how to make it compatible between unittesting and normal run

2017-11-12 06:28 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/hdbscan/hdbscan_wrapper.py
> +    from src.ml_service.global_variables.global_variable import InformationType
normal run can use the latter import method. no need for src.ml_service to be appended to the module name

2017-11-12 06:28 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/hdbscan/hdbscan_wrapper.py
> +    from src.ml_service.global_variables.global_variable import InformationType
I can look into fixing this issue

2017-11-12 06:29 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/hdbscan/hdbscan_wrapper.py
> +    from src.ml_service.global_variables.global_variable import InformationType
Test directory structure and naming are stoppers, not so much this one

2017-11-12 07:14 UTC, choitwao commented on src/ml_service/feature_extraction/preprocessing/precedence_parse.py
> +# -*- coding: utf-8 -*-
precedent_parse*
dont use plural

2017-11-12 07:15 UTC, choitwao commented
use singular for naming

2017-11-12 15:24 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/clustering/hdbscan/hdbscan_wrapper.py
> +    from src.ml_service.global_variables.global_variable import InformationType
i fixed the crying by changing my root dir to ml_service

2017-11-12 16:13 UTC, arekmano requested changes

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/Dockerfile
> +RUN python3 -c "import nltk; nltk.download('all')"
add this to init.py. And only download necessary NLTK packages. "all" takes a long time (BLOCKER)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/Dockerfile
> +RUN pip install hdbscan
why is this not it requirements.txt? (BLOCKER)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/precedent_parse.py
> +    topic --> facts --> decision --> topic...
does not apply anymore

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/precedent_parse.py
> +            return num, int(index)
why do we need both the string and int version of the number? Why not just the number?

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/precedent_parse.py
> +        Apppends topic, fact, decision to model
statement instead of enumerating statement types would make this documentation clearer (not a blocking change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/precedent_parse.py
> +    def __split_sub_sentence(self, sentence):
are we still using this? What about the list in get_stop_tokens()

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/ml_models/models.py
> +class ModelNames():
I dont understand the need for this model

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/ml_models/models.py
> +        :return: (matrix(sent vectors), list[sentences], list[filenames])
filename param comment missing(NOT a blocking change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/ml_models/models.py
> +    def load_decisions_from_bin(filename=None):
these 2 functions are very similar. Refactoring needed (NOT a blocking change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/test/feature_extraction/clustering/optimization/optimize_test.py
> +import unittest
move test to same directory of code (BLOCKING change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/test/feature_extraction/clustering/hdbscan/hdbscan_wrapper_test.py
> +import unittest
move test to same directory of code (BLOCKING change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/test/feature_extraction/preprocessing/precedence_parse_test.py
> +import unittest
move test to same directory of code (BLOCKING change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/test/feature_extraction/preprocessing/save_model_test.py
> +import unittest
move test to same directory of code (BLOCKING change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/test/init_test.py
> +import unittest
move test to same directory of code (BLOCKING change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/test/ml_models/model_test.py
> +import unittest
move test to same directory of code (BLOCKING change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/test/outputs/output_test.py
> +import unittest
move test to same directory of code (BLOCKING change)

2017-11-12 16:13 UTC, arekmano commented on src/ml_service/test/word_vectors/vectors_test.py
> +from word_vectors import vectors
move test to same directory of code (BLOCKING change)

2017-11-12 18:16 UTC, Samuel-Campbell commented on src/ml_service/Dockerfile
> +RUN pip install hdbscan
it doesn't work in req.txt

2017-11-12 18:17 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/preprocessing/precedent_parse.py
> +    def __split_sub_sentence(self, sentence):
im splitting where i see a '.'

2017-11-12 18:51 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/preprocessing/precedent_parse.py
> +            return num, int(index)
i'm splitting the sentence with it's index [num] <statement>

Once the index goes back to #1 then we are reading a new fact. This happens in 'decision rectifier'

2017-11-12 18:53 UTC, Samuel-Campbell commented on src/ml_service/ml_models/models.py
> +    def load_decisions_from_bin(filename=None):
will refactor in a new PR, I left a comment in the file to remind me

2017-11-12 19:27 UTC, Samuel-Campbell commented on src/ml_service/word_vectors/vectors.py
> +        :param word_list: String or list of tokenized words
ill refactor in a new PR

2017-11-12 20:41 UTC, arekmano commented on src/ml_service/Dockerfile
> +RUN pip install hdbscan
?? why not

2017-11-12 20:41 UTC, arekmano commented on src/ml_service/Dockerfile
> +RUN pip install hdbscan
pip install literally installs each package from the file

2017-11-12 20:42 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/precedent_parse.py
> +            return num, int(index)
I understand this. but why are we returning '#1', and 1 as a tuple?

2017-11-12 20:45 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/precedent_parse.py
> +    def __split_sub_sentence(self, sentence):
:+1:  My issue is will the use of stop tokens, not this splitting

2017-11-12 20:46 UTC, arekmano approved these changes
Good start. Needs to be refactored.

2017-11-12 21:02 UTC, Samuel-Campbell commented on src/ml_service/Dockerfile
> +RUN pip install hdbscan
it doesnt work. we tried this is why bruce spent an hour doing this

2017-11-12 21:03 UTC, merged