153/regex replace
Cyberjusticelab/JusticeAI pull request #180
Opened 2017-11-14 18:26 UTC by Samuel-Campbell

Refining Preprocessing
--------------------------------------------------------------
- Regex money
- Regex dates
- Remove unecessary white spaces
- Remove punctuation

2017-11-15 01:55 UTC, choitwao commented on src/ml_service/.gitignore
> +/word_vectors/cache.pickle
ignore?

2017-11-15 01:55 UTC, choitwao commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    date_match = re.compile('(\d+?\w*?\s+?|)(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)(\s+\d{2,4}|)')
I am not sure if such thing exists in python: making these regex pattern somewhere in a json or enum to make the code more sturctured

2017-11-15 02:24 UTC, arekmano requested changes

2017-11-15 02:24 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/optimization/optimize.py
> +
rm

2017-11-15 02:24 UTC, arekmano commented on src/ml_service/feature_extraction/main.py
> +        save_model.save()
?

2017-11-15 02:24 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    date_match = re.compile('(\d+?\w*?\s+?|)(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)(\s+\d{2,4}|)')
no. this is the cleanest way to do it. a class variable

2017-11-15 02:24 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
\d+\s*?\$

2017-11-15 03:05 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/main.py
> +        save_model.save()
don't need the second argument to binarize precedent anymore

2017-11-15 03:05 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/clustering/optimization/optimize.py
> +
why would I remove this? i use it almost every day

2017-11-15 04:53 UTC, arekmano commented on src/ml_service/feature_extraction/clustering/optimization/optimize.py
> +
the empty spaces only 😄

2017-11-15 18:35 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/clustering/optimization/optimize.py
> +
Auto pep8 dos this. You need a new line at the end of every file

2017-11-16 00:10 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
????

2017-11-16 00:10 UTC, arekmano commented on src/ml_service/word_vectors/related_word_fetcher.py
> +        #logger.info("Querying Wikitionary: " + requestURL)
rm commented out things

2017-11-16 00:20 UTC, mihaiqc commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
I disagree with both and propose
(\d+([,,.]\d{1,2})?)\$

2017-11-16 00:23 UTC, mihaiqc commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    date_match = re.compile('(\d+?\w*?\s+?|)(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)(\s+\d{2,4}|)')
Careful this doesn't cover capital letters if a sentence starts with a capital

Ez fix: [J,j]anvier , etc.

2017-11-16 00:24 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
does not match the following:
23$
23.00 $

Why {1,2}?
why are there 2 , in [,,.]

2017-11-16 00:27 UTC, mihaiqc commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
number (coma or dot) 2 numbers (number with decimals) followed by dollar sign

Honestly not too sure why github is eating my backslash before the $ sign but it's missing.

2017-11-16 00:30 UTC, mihaiqc commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
![stuff](https://i.imgur.com/XrFqnlp.png)

2017-11-16 00:38 UTC, mihaiqc commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    date_match = re.compile('(\d+?\w*?\s+?|)(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)(\s+\d{2,4}|)')
Also quick inquiry, did you ever see the month name be abbreviated in your readings?
Like Jan instead of Janvier?

2017-11-16 01:25 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
then it should be as follows
<code>(\d+([,.]\d{1,2}){0,1})\s*\$</code>

2017-11-16 01:33 UTC, mihaiqc commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
Your expression doesn't pick up the first number. Effectively if a string has one variable, it will never pick it up with that regex. If a string has two money amounts, it will only pick up the second one.

2017-11-16 01:40 UTC, Vynny commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
This one is promising:
<code>([^\D][\d\s+|\d[,\d{2}]+?\$)</code>
Tried it and it works with several examples from the data. 
Only problem is in a case like this:
2,88 $ 50
12 224,48 $
It will match 2,88 $, and 50
12 224,48 $.
Trying to find a fix for this.

2017-11-16 01:45 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    date_match = re.compile('(\d+?\w*?\s+?|)(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)(\s+\d{2,4}|)')
nope. also, all the text is lowercase

2017-11-16 01:46 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
@mihaiqc yes it does... the first \d+

2017-11-16 01:47 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
![image](https://user-images.githubusercontent.com/8740734/32869669-407d9904-ca46-11e7-9508-16d8bb394712.png)

2017-11-16 01:48 UTC, mihaiqc commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
![image](https://user-images.githubusercontent.com/9852083/32869678-4dcc45e2-ca46-11e7-916c-433598463bfe.png)

?

2017-11-16 01:49 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
@Vynny you are misusing [ ], unless i misunderstand your regex. groups must be ( )

2017-11-16 01:50 UTC, Vynny commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
The data doesn't use that format. Examples:
600,00 $
2 195 $
12 224,48 $
2 $

2017-11-16 01:52 UTC, Vynny commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
![data](https://user-images.githubusercontent.com/1418403/32869806-ec5665d0-ca46-11e7-99ec-8d8c81d13949.PNG)

2017-11-16 01:54 UTC, arekmano commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
:+1:  Concede

2017-11-16 01:59 UTC, mihaiqc commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
Literally getting different results with different regular expression. This is a problem.
![image](https://user-images.githubusercontent.com/9852083/32869988-d2bf0e00-ca47-11e7-9719-87e953402c45.png)

2017-11-16 03:18 UTC, Vynny commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
<code>\b(\d{1,3}(\$|\s\$|\s(?=\d)|,(?=\d)))+</code>

2017-11-16 03:19 UTC, Vynny commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
![data](https://user-images.githubusercontent.com/1418403/32872124-07ceffaa-ca53-11e7-944a-6faa161dac65.PNG)

2017-11-16 14:26 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
ok thanks vynny i will add that tonight

2017-11-16 19:45 UTC, choitwao commented
If you replace the date and $ in pre-processing, that means the precedents (binary) and clusters will not include the original sentences. In the future when we input the new data for prediction we also need to preprocess it in this way.

2017-11-16 19:50 UTC, choitwao commented
If the $ is replaced as well, how do we extract values?

2017-11-16 20:05 UTC, Vynny commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
Don't yet, it needs a few tweaks. I found that it gives some false positives in the documents.

2017-11-16 20:25 UTC, Vynny commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
This one is more complete and handles more edge cases:
<code>\b(\d{1,3}(\s\d{3}|,\d{2})*)+(?=(\$|\s\$))</code>

2017-11-16 23:51 UTC, Samuel-Campbell commented
@choitwao I only replace $ and dates in preprocessing to create my sentence vectors. I write the original text in the files

2017-11-17 00:06 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
doesn't work

2017-11-17 00:09 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/preprocessing/regex_replacer.py
> +    money_match = re.compile('[\d*\s*,*]*\$')
it doesn't work. The one I wrote works. I don't know why we are trying to change it

2017-11-17 03:30 UTC, arekmano approved these changes
looks good!

2017-11-17 04:29 UTC, merged