[#151] Precedents data structure
Cyberjusticelab/JusticeAI pull request #188
Opened 2017-11-16 06:21 UTC by Taimoorrana1

- Created structure for precedent data
- This data can also be outputted as JSON

**Precedent data structure:**
```
{
"AZ-123456":{
              "facts": [(0,"some fact"),(10,"another fact with different category")...]
              "facts_vector": [0,1,1,1,1,1,0,0,0,1,0]
              "outcomes": [(0,"some fact"),(10,"another fact with different category")...]
              "outcomes_vector": [0,1,1,1,1,1,0,0,0,1,0]
              "lease_terminated": None
            }
"AZ-1234567":{
              "facts": [(0,"some fact"),(10,"another fact with different category")...]
              "facts_vector": [0,1,1,1,1,1,0,0,0,1,0]
              "outcomes": [(0,"some fact"),(10,"another fact with different category")...]
              "outcomes_vector": [0,1,1,1,1,1,0,0,0,1,0]
              "lease_terminated": None
            }
}
```

2017-11-16 14:29 UTC, Samuel-Campbell commented
I disagree. 

"AZ-123456":{
              "facts": [(0,"some fact"),(10,"another fact with different category")...]
              "facts_vector": [0,1,1,1,1,1,0,0,0,1,0]
              "outcomes": [(0,"some fact"),(10,"another fact with different category")...]
              "outcomes_vector": [0,1,1,1,1,1,0,0,0,1,0]
              **"lease_terminated": None --> DON'T NEED THIS**
            }

2017-11-16 14:31 UTC, Samuel-Campbell requested changes

2017-11-16 14:31 UTC, Samuel-Campbell commented on src/ml_service/precedents/structured_precedents.py
> +    def __init__(self, fact_labels, fact_data_tuple, outcome_labels, outcome_data_tuple):
No. It seems to be like you want to load the precedent binaries. Use the Cluster models instead.

2017-11-16 14:32 UTC, Samuel-Campbell requested changes

2017-11-16 14:32 UTC, Samuel-Campbell commented on src/ml_service/precedents/structured_precedents.py
> +            json.dump(self.precedents, output_file)
Add unittesting

2017-11-16 14:36 UTC, Samuel-Campbell requested changes

2017-11-16 14:36 UTC, Samuel-Campbell commented on src/ml_service/precedents/structured_precedents.py
> +                    # initialize fields
Do not use lists. Use numpy arrays.

2017-11-16 14:41 UTC, Samuel-Campbell commented on src/ml_service/precedents/structured_precedents.py
> +        unique_labels = set(labels)
the labels are only integers from -1 to n with no significance. 
set(labels) won't do anything because all labels are unique

2017-11-16 15:55 UTC, Taimoorrana1 commented on src/ml_service/precedents/structured_precedents.py
> +    def __init__(self, fact_labels, fact_data_tuple, outcome_labels, outcome_data_tuple):
yes, but I also need the cluster labels and for that, some X clusters need to run. So this way, the class can be used by any Clusters. Just the precedent binaries aren't enough. What do you think?

2017-11-16 15:55 UTC, Taimoorrana1 commented on src/ml_service/precedents/structured_precedents.py
> +            json.dump(self.precedents, output_file)
Will do

2017-11-16 15:57 UTC, arekmano commented
Save as pickle too please. More efficient to load

2017-11-16 15:57 UTC, arekmano requested changes
Pickle

2017-11-16 16:05 UTC, TaimoorRana commented
@Samuel-Campbell please see #151 for _"lease_terminated": None --> don't need. It's represented in the outcomes_

2017-11-16 16:08 UTC, Taimoorrana1 commented on src/ml_service/precedents/structured_precedents.py
> +        unique_labels = set(labels)
Yes but I don't want repetitions

2017-11-16 16:14 UTC, Samuel-Campbell commented on src/ml_service/precedents/structured_precedents.py
> +    def __init__(self, fact_labels, fact_data_tuple, outcome_labels, outcome_data_tuple):
I don't understand what you are trying to say. what are you trying to do exactly? bullet pts

2017-11-16 16:15 UTC, Samuel-Campbell commented
@Taimoorrana1 it's only a suggested template. We don't actually need that value because we should know it's index in the array

2017-11-16 16:32 UTC, Taimoorrana1 commented on src/ml_service/precedents/structured_precedents.py
> +    def __init__(self, fact_labels, fact_data_tuple, outcome_labels, outcome_data_tuple):
this need clusters labels, which we get after a cluster runs

2017-11-16 16:36 UTC, Taimoorrana1 commented on src/ml_service/precedents/structured_precedents.py
> +    def __init__(self, fact_labels, fact_data_tuple, outcome_labels, outcome_data_tuple):
I need the category (labels) for each fact and outcome to create the vectors. These labels are produced after a cluster has run.

2017-11-16 16:44 UTC, arekmano commented
Though it may correspond to multiple clusters I think it's correct like this

2017-11-16 19:29 UTC, Samuel-Campbell commented on src/ml_service/precedents/structured_precedents.py
> +        unique_labels = set(labels)
ohhh ok I see what you're doing now

2017-11-16 19:29 UTC, Samuel-Campbell commented on src/ml_service/precedents/structured_precedents.py
> +    def __init__(self, fact_labels, fact_data_tuple, outcome_labels, outcome_data_tuple):
It's ok i see what you're doing. I had a hard time understanding at first

2017-11-16 19:42 UTC, choitwao commented on src/ml_service/precedents/structured_precedents.py
> +    CATEGORY_INDEX = 0
i think we should formalize what we use for naming to avoid confusion. `category`? `label`? `feature`?

2017-11-16 19:42 UTC, choitwao commented on src/ml_service/precedents/structured_precedents.py
> +                # populate fields
Do we need this? I think the vectors are already referring the facts in the clusters.

2017-11-16 20:12 UTC, Taimoorrana1 commented on src/ml_service/precedents/structured_precedents.py
> +                # populate fields
which vectors?

2017-11-16 22:55 UTC, arekmano approved these changes
LGTM

2017-11-16 23:09 UTC, dodoels approved these changes

2017-11-17 00:30 UTC, Samuel-Campbell approved these changes

2017-11-17 01:52 UTC, arekmano commented on src/ml_service/precedents/structured_precedents.py
> +    FACTS = "facts"
not needed. 1s and 0s are all I need

2017-11-17 01:52 UTC, arekmano commented on src/ml_service/precedents/structured_precedents.py
> +    DECISIONS = "decisions"
not needed. 1s and 0s are all I need

2017-11-17 01:54 UTC, arekmano commented on src/ml_service/precedents/structured_precedents.py
> +                    self.precedents[file_name][self.FACTS] = []
don't need these, keep binary small

2017-11-17 01:54 UTC, arekmano commented on src/ml_service/precedents/structured_precedents.py
> +                    self.precedents[file_name][self.DECISIONS] = []
don't need these, keep binary small

2017-11-17 02:44 UTC, Taimoorrana1 commented on src/ml_service/precedents/structured_precedents.py
> +    DECISIONS = "decisions"
removed

2017-11-17 02:44 UTC, Taimoorrana1 commented on src/ml_service/precedents/structured_precedents.py
> +    FACTS = "facts"
removed

2017-11-17 03:07 UTC, merged