153/regex facts
Cyberjusticelab/JusticeAI pull request #192
Opened 2017-11-18 17:08 UTC by Samuel-Campbell

- Skeleton for regex
- just add regex to the list of RegexLib to add facts

2017-11-19 18:01 UTC, dodoels requested changes
Remove data from PR

2017-11-19 18:41 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        #("tenant_request_cancel_lease", re.compile(r"")),
please remove all commented code

2017-11-19 18:46 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/data/demands/0-tenant_eviction.txt
> +Le locateur demande la résiliation du bail et l'expulsion des locataires
Why are we uploading all of these?

2017-11-19 18:55 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        #("tenant_request_cancel_lease", re.compile(r"")),
no

2017-11-19 18:55 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/data/demands/0-tenant_eviction.txt
> +Le locateur demande la résiliation du bail et l'expulsion des locataires
yeah we will upload them on the server

2017-11-19 18:56 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/data/demands/0-tenant_eviction.txt
> +Le locateur demande la résiliation du bail et l'expulsion des locataires
i will need to rebase

2017-11-19 18:59 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        #("tenant_request_cancel_lease", re.compile(r"")),
yes!

2017-11-19 19:03 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/data/demands/0-tenant_eviction.txt
> +Le locateur demande la résiliation du bail et l'expulsion des locataires
But why do we need to upload them?

2017-11-19 19:05 UTC, TaimoorRana requested changes
please remove all commented code. We need to keep the code base as clean as possible.

2017-11-19 19:19 UTC, TaimoorRana submitted a review, later dismissed

2017-11-19 23:03 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("landlord_fix_rent", re.compile(r".*(locat(eur(s)?|rice(s)?)).+(demand(e|ent)).+(fix(er|ation)).+loyer")),
why are we not ignoring case for this one?

2017-11-19 23:46 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("landlord_is_violent", re.compile(r".*violentée|violent(e)?|menaçant(e)?.*"), re.IGNORECASE),
The 2 above are identical

2017-11-20 15:07 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("landlord_fix_rent", re.compile(r".*(locat(eur(s)?|rice(s)?)).+(demand(e|ent)).+(fix(er|ation)).+loyer")),
forgot to

2017-11-22 20:00 UTC, Taimoorrana1 commented
Closed as it was merged with #183

2017-11-22 20:01 UTC, Taimoorrana1 commented
Closed as it was merged with #183

2017-11-22 20:01 UTC, closed without merging