183/unification
Cyberjusticelab/JusticeAI pull request #193
Opened 2017-11-18 22:37 UTC by choitwao

- [ ] refactor the directory

2017-11-19 14:43 UTC, choitwao commented
please ignore all test files for now

2017-11-21 00:02 UTC, Samuel-Campbell commented
Helping bruce with this on wednesday. Not ready for merge

2017-11-22 20:53 UTC, Samuel-Campbell approved these changes
looks good

2017-11-22 21:28 UTC, arekmano requested changes

2017-11-22 21:28 UTC, arekmano commented on src/ml_service/feature_extraction/post_processing/post_processing.py
> +    fact_data_tuple = Load.load_binary("facts_pre_processed.bin")
no more load_binary please. all should be done in one shot

2017-11-22 21:28 UTC, arekmano commented on src/ml_service/outcome_predictor/basic_neural_net.py
> -from keras.models import Sequential
why is this deleted?

2017-11-22 21:54 UTC, choitwao commented on src/ml_service/outcome_predictor/basic_neural_net.py
> -from keras.models import Sequential
We thought we are not using it anymore, do you want me to put it back?

2017-11-22 21:55 UTC, choitwao commented on src/ml_service/feature_extraction/post_processing/post_processing.py
> +    fact_data_tuple = Load.load_binary("facts_pre_processed.bin")
You need to load binaries to create precedent vector lol

2017-11-22 21:56 UTC, Samuel-Campbell commented on src/ml_service/outcome_predictor/basic_neural_net.py
> -from keras.models import Sequential
it's also not unittested

2017-11-22 21:57 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/post_processing/post_processing.py
> +    fact_data_tuple = Load.load_binary("facts_pre_processed.bin")
I don't understand what you mean by no more binary

2017-11-22 23:13 UTC, arekmano approved these changes

2017-11-22 23:51 UTC, merged