[#183] Created regex rules for fact extraction
Cyberjusticelab/JusticeAI pull request #194
Opened 2017-11-19 00:02 UTC by arekmano

[#183] Not yet ready for PR

2017-11-20 15:30 UTC, Samuel-Campbell requested changes

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +            if count > 20:
What is this? you can just specify a number of files

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("demand_resiliation", [re.compile(r"\[[123]\].+(demande|réclame)(nt|) la résiliation du bail"),
remove this regex, we already specify tenant, landord in ours

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("demand_lease_modification", [re.compile(r"\[[123]\].+produit une demande en modifications du bail")], re.IGNORECASE),
need to know if tenant or landlord, add unittest for it

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("landlord_demand_access_rental", [re.compile(r"\[[123]\].+accès au logement")], re.IGNORECASE),
find word locateur in regex please

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +                                       re.compile(r"\[[123]\].+recouvrement (de loyer|du loyer|d\'une somme)"),
add locateur in regex

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("absent", [re.compile(r"\[\d+\].+considérant l\'absence (du|de la|des) locat(eur|rice|aire)(s|)")], re.IGNORECASE),
tenant_is_absent

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("bothers_others", [re.compile(r"\[\d+\].+locataire(s|) trouble(nt|) la jouissance normale des lieux loués"),
tenant_bothers_others
keep standard format name

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("disrespect_previous_judgement", [re.compile(r"\[\d+\].+non-respect d\'une ordonnance émise antérieurement"),
tenant or landlord

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("incorrect_facts", [re.compile(r"\[\d+\].+demande (de la|des) locataire(s|) est mal fondée")], re.IGNORECASE),
don't think it's necessary. we assume what the user says is true

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("proof_of_late", [re.compile(r"\[\d+\].+une reconnaissance de dette")], re.IGNORECASE),
same as tenant_owes_money

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("proof_of_revenu", [re.compile(r"\[\d+\].+a fourni (\w+\s){0,10}l\'attestation de ses revenu")], re.IGNORECASE),
remove [\d+\]
not all lines have it

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("rent_increased", [re.compile(r"\[\d+\].+preuve démontre la réception de l\'avis d\'augmentation")], re.IGNORECASE),
remove remove [\d+]

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("tenant_damaged_rental", [re.compile(r"\[\d+\].+locataire (a|ont) causé des dommages")], re.IGNORECASE),
remove [\d+]

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("tenant_dead", [re.compile(r"\[\d+\].+locataire(s|) (est|sont) décédé(e|s|es)")], re.IGNORECASE),
remove [\d+]

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("three_weeks_late", [re.compile(r"\[\d+\].+locataire(s|) (est|sont) en retard (\w+(\s|\'|,\s)){1,8}(trois|3) semaines")], re.IGNORECASE),
same as tenant_not_pad_3_weeks

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/regex_demand.py
> +def get_ask_lease_modification():
remove these methods

2017-11-20 15:30 UTC, Samuel-Campbell commented on src/ml_service/regex_demand.py
> +                if reg.search(s):
please use reg.match
reg.search is inferior for this task.
intent : infestation has 'rat' 
this will be found in the word Administrative.

2017-11-20 15:31 UTC, Samuel-Campbell commented
remove all  remove [\d+] and add unittest for all new regex. Just create files with examples

2017-11-20 15:35 UTC, Samuel-Campbell requested changes

2017-11-20 15:35 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("landlord_demand_retake_apartment", [re.compile(r".*(locat(eur(s)?|rice(s)?)).*demand(e|ent).+(autoris(er|ation)).+reprendre.+logement"),
this won't work with my code. the list inside the tuple.

2017-11-20 15:35 UTC, Samuel-Campbell commented on src/ml_service/regex_demand.py
> +import os
remove this file entirely. My code already creates the matrix of tags

2017-11-20 15:35 UTC, Samuel-Campbell commented on src/ml_service/train.py
> +def load_new_data(data_set):
No. Put this code in ml_models/model.py

2017-11-20 15:35 UTC, Samuel-Campbell commented on src/ml_service/train.py
> +    """
put this in ml_models

2017-11-20 16:31 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("tenant_dead", [re.compile(r"\[\d+\].+locataire(s|) (est|sont) décédé(e|s|es)")], re.IGNORECASE),
\[\d+\] and \[123\] were left there on purpose so we can differentiate Arek's regexes from yours. Like this, we can see if they were merged correctly in the same category. Once confirmed, I will remove them

2017-11-20 16:33 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +            if count > 20:
This was for testing purposes, left it by accident.

2017-11-20 16:33 UTC, Taimoorrana1 commented on src/ml_service/regex_demand.py
> +def get_ask_lease_modification():
not yet, they still need to transferred to regex_lib

2017-11-20 16:34 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("landlord_demand_retake_apartment", [re.compile(r".*(locat(eur(s)?|rice(s)?)).*demand(e|ent).+(autoris(er|ation)).+reprendre.+logement"),
I have updated your code, please check

2017-11-20 17:05 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("incorrect_facts", [re.compile(r"\[\d+\].+demande (de la|des) locataire(s|) est mal fondée")], re.IGNORECASE),
We are not deciding if the user is telling the truth or not, this is what the judge said. This is important

2017-11-20 17:06 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("tenant_damaged_rental", [re.compile(r"\[\d+\].+locataire (a|ont) causé des dommages")], re.IGNORECASE),
[\d+] and [123] were left there on purpose so we can differentiate Arek's regexes from yours. Like this, we can see if they were merged correctly in the same category. Once confirmed, I will remove them

2017-11-20 17:06 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("rent_increased", [re.compile(r"\[\d+\].+preuve démontre la réception de l\'avis d\'augmentation")], re.IGNORECASE),
[\d+] and [123] were left there on purpose so we can differentiate Arek's regexes from yours. Like this, we can see if they were merged correctly in the same category. Once confirmed, I will remove them

2017-11-20 17:06 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("proof_of_revenu", [re.compile(r"\[\d+\].+a fourni (\w+\s){0,10}l\'attestation de ses revenu")], re.IGNORECASE),
[\d+] and [123] were left there on purpose so we can differentiate Arek's regexes from yours. Like this, we can see if they were merged correctly in the same category. Once confirmed, I will remove them

2017-11-20 17:16 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("absent", [re.compile(r"\[\d+\].+considérant l\'absence (du|de la|des) locat(eur|rice|aire)(s|)")], re.IGNORECASE),
This is looking for all of them `locat(eur|rice|aire)` tenant and landlord. Will need to separate into `tenant_is_absent` and `landlord_is_absent`

2017-11-20 17:19 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("incorrect_facts", [re.compile(r"\[\d+\].+demande (de la|des) locataire(s|) est mal fondée")], re.IGNORECASE),
changed to `tenant_incorrect_facts`

2017-11-20 17:25 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("proof_of_late", [re.compile(r"\[\d+\].+une reconnaissance de dette")], re.IGNORECASE),
good catch

2017-11-20 17:29 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("three_weeks_late", [re.compile(r"\[\d+\].+locataire(s|) (est|sont) en retard (\w+(\s|\'|,\s)){1,8}(trois|3) semaines")], re.IGNORECASE),
I think this is for exactly 3 weeks. @arekmano can you confirm?

2017-11-21 02:20 UTC, arekmano commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("demand_resiliation", [re.compile(r"\[[123]\].+(demande|réclame)(nt|) la résiliation du bail"),
I disagree. We should keep tenant or landlord is asking as one fact. and resiliation as the demand

2017-11-21 02:33 UTC, arekmano commented on src/ml_service/feature_extraction/regex/regex_lib.py
> +        ("tenant_damaged_rental", [re.compile(r"\[\d+\].+locataire (a|ont) causé des dommages")], re.IGNORECASE),
disagree. \[\d+\] makes sure that the text is within a fact. There are some quotes that people say that we don't care about

2017-11-21 06:13 UTC, arekmano commented
Most of the regexes will need to be reworked.

2017-11-21 06:56 UTC, arekmano reviewed
.

2017-11-21 06:56 UTC, arekmano commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +        for line in file:
Changing this so we only go through the fact lines can make the regexing go significantly faster

2017-11-21 14:23 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +        for line in file:
yes I did that originally to check the lines that get tagged. but you can reduce complexity by an order of magnitude

2017-11-21 14:39 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +                matchFound = False
this is also a mistake I made. Some lines have more than 1 fact.

2017-11-21 18:07 UTC, arekmano commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +                matchFound = False
Yes. This is so that the regex iteration stops for the same fact.

2017-11-21 19:21 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +                        matchFound = True
Simple break statement would be better instead of `matchFound`

2017-11-21 21:48 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +                matchFound = False
oh nvm I missunderstood this section I thought it was doing something else

2017-11-22 02:45 UTC, arekmano commented
Refactor complete. Please re-review :smile:

2017-11-22 03:51 UTC, Taimoorrana1 commented on src/ml_service/train.py
> +    # for file_name in fact_vectors.keys():
Please remove commented code

2017-11-22 03:54 UTC, Samuel-Campbell requested changes
Remove unittest files

2017-11-22 04:44 UTC, TaimoorRana approved these changes

2017-11-22 04:45 UTC, TaimoorRana approved these changes

2017-11-22 17:39 UTC, TaimoorRana requested changes
Need to remove regexes

2017-11-22 17:39 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +        :param enum: TagEnum --> Init default tagger
Update doc

2017-11-22 20:56 UTC, Samuel-Campbell approved these changes

2017-11-22 21:35 UTC, TaimoorRana approved these changes

2017-11-22 21:46 UTC, arekmano reviewed
Minor change

2017-11-22 21:46 UTC, arekmano commented on src/ml_service/.gitignore
> +/outputs/fact_matrix_dir/
outputs/precedent_dict should be the saving location

2017-11-22 21:46 UTC, arekmano commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +    dict = tag.tag_precedents()
change from dict to something else. it is a keyword in python

2017-11-22 21:55 UTC, Taimoorrana1 commented on src/ml_service/.gitignore
> +/outputs/fact_matrix_dir/
Maybe instead of precedent_dict we should use fact_dict because this doesn't have decisions and the name will be confused with the other precedent_vector (created from clusters)

2017-11-22 21:55 UTC, Taimoorrana1 commented on src/ml_service/.gitignore
> +/outputs/fact_matrix_dir/
or even fact_vector

2017-11-23 00:28 UTC, arekmano reviewed
merging issues

2017-11-23 00:28 UTC, arekmano commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +        self.regexes = Load.load_model_from_bin(Load.regexes)
seems to be lost in merge

2017-11-23 00:28 UTC, arekmano commented on src/ml_service/train.py
> +    fact_vectors = Load.load_model_from_bin(Load.regex_vectors)
Load.regex_vectors seems to be lost in merge

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +# -*- coding: utf-8 -*-
move `ml_service/feature_extraction/regex/regex_facts.py` to `ml_service/feature_extraction/post_processing/regex/regex_facts.py`

change `facts` to `fact` for naming convention (use singular for consistency)

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +        self.precedents_directory_path = Global.precedent_directory
`Path.raw_directory`

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/outcome_predictor/svm.py
> +from sklearn import svm
move `ml_service/outcome_predictor/svm.py` to `ml_service/model_learning/svm/svm.py`, same for test file

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/outcome_predictor/svm.py
> +        print("Sample size: {}".format(len(x_total)))
use `from util.log import Log` and `Log.write()`

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/outcome_predictor/svm.py
> +
add `from util.file import Save`
add `s = Save()`, `s.save_binary("svm_model.bin")`, `return clf`

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/outcome_predictor/svm.py
> +    def evaluate_best_parameters(self):
where is this method being used?

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +if __name__ == '__main__':
I will move this block of codes to drive, you can keep it

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/test_data/sample_precedent/1.txt
> +
remove test file

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/test_data/sample_precedent/2.txt
> +
remove test file

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/train.py
> +import numpy as np
move `ml_service/train.py` to be `ml_service/model_learning/model_learning.py`

2017-11-23 00:42 UTC, choitwao commented on src/ml_service/feature_extraction/regex/regex_facts_test.py
> +        self.precedent_tagger.precedents_directory_path = Global.test_data_directory + "sample_precedent/"
Can you write a short mock precedent within the test file instead of using real precedent?

2017-11-23 00:43 UTC, choitwao commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +        self.regexes = Load.load_model_from_bin(Load.regexes)
`Load.load_binary("file_name.bin"`)

2017-11-23 00:54 UTC, choitwao commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +from file import Load
`from util.file import Save, Load`

2017-11-23 00:54 UTC, choitwao commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +        self.regexes = Load.load_binary("/Users/taimoorrana/Documents/JusticeAI/src/ml_service/ml_models/regexes.bin")
rename `regexes.bin` to `precedent_regex.bin`, place it in `ml_service/data/binary`, and change this line to `Load.load_binary("precedent_regex.bin")`.  `load_binary` will automatically load from such path so the path doesn't need to be specified.

2017-11-23 00:55 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/regex/regex_facts.py
> +        self.regexes = Load.load_binary("/Users/taimoorrana/Documents/JusticeAI/src/ml_service/ml_models/regexes.bin")
that was a mistake. please wait. pushing soon

2017-11-23 01:06 UTC, arekmano commented on src/ml_service/outcome_predictor/svm.py
> +    def evaluate_best_parameters(self):
it is used for evaluating parameters. These are later hardcoded. Not used during run-time, but run manually.

2017-11-23 01:17 UTC, choitwao commented on src/ml_service/util/constant.py
> +    __rel_path = r'data/raw/text_bk/'
the above path `data/raw` is already for precedent. We don't keep `text_bk` anymore. Simply just extract the precedent text files to `data/raw`

2017-11-23 03:47 UTC, merged