[#65] Implements a basic outlier detection system for user messages with RASA training data as input.
Cyberjusticelab/JusticeAI pull request #195
Opened 2017-11-19 17:56 UTC by lancelafontaine

[#65] 

- [x] Implements a basic outlier detection system for user messages with RASA training data as input.

Our input data set is quite small, making the outlier detection reject most responses. We will need to either generate lots more sentences ourselves as RASA training data, or eventually base it off user-provided data.

2017-11-20 21:20 UTC, Samuel-Campbell commented on src/nlp_service/controllers/nlpController.py
> +    if False:
?

2017-11-20 21:20 UTC, Samuel-Campbell commented
looks good except for that weird if False

2017-11-20 21:20 UTC, Samuel-Campbell approved these changes

2017-11-20 21:22 UTC, lancelafontaine commented on src/nlp_service/controllers/nlpController.py
> +    if False:
Outlier detection will be turned off until we amass enough user-generated data for it to be useful.

Until then, we also want all inputs to be accepted (during the beta testing).

2017-11-20 22:57 UTC, Vynny commented on src/nlp_service/controllers/nlpController.py
> +    if False:
I think that this should be a config setting when starting the application. However, it can be implemented in another pr.

I don't like this because it essentially renders the application un-demoable unless you change code.

2017-11-22 21:42 UTC, arekmano requested changes

2017-11-22 21:42 UTC, arekmano commented on src/nlp_service/outlier/outlier_detection.py
> +        from sklearn.feature_extraction.text import TfidfVectorizer
import at the top

2017-11-22 21:42 UTC, arekmano commented on src/nlp_service/outlier/outlier_detection.py
> +        from sklearn.covariance import EllipticEnvelope
import at Top

2017-11-22 21:42 UTC, arekmano commented on src/nlp_service/outlier/outlier_detection.py
> +import pickle
use Joblib. more efficient for large arrays.

2017-11-22 21:42 UTC, arekmano commented on src/nlp_service/controllers/nlpController.py
> +outlier_detector = OutlierDetection()
load from disk using joblib or pickle. Faster than retraining.

2017-11-23 01:33 UTC, lancelafontaine commented on src/nlp_service/controllers/nlpController.py
> +outlier_detector = OutlierDetection()
Instantiating the object doesn't retrain. It's only retrained when calling `initialize_fact_model`, and the latest changes never call that (use a bin instead).

2017-11-23 01:48 UTC, arekmano requested changes

2017-11-23 01:48 UTC, arekmano commented on src/nlp_service/outlier/outlier_detection.py
> +        self.ensure_models_loaded()
wouldn't it make more sense to load the model when the flask app is initialized?

2017-11-23 01:49 UTC, arekmano commented on src/nlp_service/outlier/outlier_detection.py
> +        self.ensure_models_loaded()
doing it this was will make the first request wait for the model to be loaded.

2017-11-23 03:06 UTC, arekmano approved these changes
LGTM

2017-11-23 03:11 UTC, merged