[#183] Added primary ML endpoint to readme.
Cyberjusticelab/JusticeAI pull request #198
Opened 2017-11-22 20:40 UTC by arekmano

[#183]

2017-11-22 20:57 UTC, Samuel-Campbell commented on src/ml_service/README.md
> +    "demand_lease_modification": 1,
why are all the values 1?

2017-11-22 20:58 UTC, choitwao commented
@arekmano it is a bit confusing if you have all `1` as the value, can you change some to `0` instead

2017-11-22 21:31 UTC, arekmano commented on src/ml_service/README.md
> +    "demand_lease_modification": 1,
dummy example

2017-11-22 21:33 UTC, arekmano commented on src/ml_service/README.md
> +    "demand_lease_modification": 1,
updated

2017-11-22 22:46 UTC, dodoels approved these changes

2017-11-22 23:39 UTC, lancelafontaine commented
This is only one of the many endpoints that would be required for integration with `nlp_service` right? `nlp_service` will (eventually) need a way to know what fact to ask the user next.

2017-11-22 23:44 UTC, arekmano commented
yes. This is the initial api that we can demo this iteration. we will later need an next_fact endpoint or similar

2017-11-23 04:19 UTC, ghost requested changes
Code Cov bug...?

2017-11-23 05:00 UTC, ghost approved these changes

2017-11-23 05:21 UTC, merged