45/submit button
Cyberjusticelab/JusticeAI pull request #224
Opened 2017-12-21 14:17 UTC by Samuel-Campbell

Not merge ready

2017-12-21 14:18 UTC, Samuel-Campbell commented
![screenshot from 2017-12-21 09-17-32](https://user-images.githubusercontent.com/16637820/34259325-df83f246-e62f-11e7-82e7-8a82e2b298d3.png)
![screenshot from 2017-12-21 09-17-46](https://user-images.githubusercontent.com/16637820/34259326-dfa2c00e-e62f-11e7-89bc-8f7e14ff06b0.png)
![screenshot from 2017-12-21 09-17-53](https://user-images.githubusercontent.com/16637820/34259327-dfbd0e8c-e62f-11e7-806c-63b6c9bb6341.png)

2017-12-21 16:36 UTC, arekmano commented
UI LGTM

2017-12-21 17:12 UTC, Vynny requested changes

2017-12-21 17:12 UTC, Vynny commented on src/postgresql_db/models.py
> +    feedback = db.Column(db.String(250), nullable=False)
This should be db.Text() if we aren't imposing length limits.

2017-12-21 17:12 UTC, Vynny commented on src/web_client/src/components/Sidebar.vue
> +            var feedback = document.getElementById("feedback-text").value;
This does not leverage vue.js. You should add do this by either passing the value into the function on submit, or add a feedback object to 'data' then bind it to the input with v-model. Then in the method you can do 'this.feedback.text' to retrieve the text.

2017-12-21 17:12 UTC, Vynny commented on src/web_client/src/components/Sidebar.vue
> +                    document.getElementById("feedback-text").value = "";
Same as above, this should be bound to a model and not done with plain js.

2017-12-21 17:13 UTC, Vynny commented on src/web_client/src/components/Sidebar.vue
> +            var feedback = document.getElementById("feedback-text").value;
You can see an example of this here: 
https://stackoverflow.com/a/45840995
https://vuejs.org/v2/guide/forms.html

2017-12-21 17:51 UTC, arekmano commented on src/web_client/src/components/Sidebar.vue
> +                    document.getElementById("feedback-text").value = "";
+1

2017-12-21 21:16 UTC, choitwao commented on src/web_client/src/components/Sidebar.vue
> +            dialogVisible: false,
`openFeedbackModal` for consistent naming convention (start with verb)

2017-12-21 21:16 UTC, choitwao commented on src/web_client/src/components/Sidebar.vue
> +                <textarea id="feedback-text">
1. in `data ()`, in `user` object, create new value `feedback` 
2. add `v-model="user.feedback"`

2017-12-21 21:16 UTC, choitwao commented on src/web_client/src/components/Sidebar.vue
> +                data: feedback
3. `data: this.user.feedback`

2017-12-21 21:16 UTC, choitwao commented on src/web_client/src/components/Sidebar.vue
> +                    document.getElementById("feedback-text").value = "";
4. `this.user.feedback == null`

2017-12-22 01:44 UTC, Vynny approved these changes

2017-12-22 04:07 UTC, dodoels approved these changes
LGTM, I will add unit test and improve the code a bit later

2017-12-22 15:55 UTC, merged