[#251] refactored code to accomodate new data structure
Cyberjusticelab/JusticeAI pull request #292
Opened 2018-01-20 22:39 UTC by Samuel-Campbell

1) Refactored training_driver 
2) added comments in regex files
3) Slightly touched svm.py

2018-01-21 15:55 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_tagger.py
> +        # ----------------------- 1 -----------------------------#
+1 for awesome comments

2018-01-22 16:26 UTC, Vynny approved these changes

2018-01-22 18:21 UTC, dodoels approved these changes
Looking code overall, would love to see some console log to see its actual output

2018-01-22 18:21 UTC, dodoels commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                sentence = regex_result.group(0)
suggest `matched_sentence` in case of confusion. It is a bit confused we have `word`, `text`, `sentence` variable names without knowing the context

2018-01-22 18:21 UTC, dodoels commented on src/ml_service/feature_extraction/post_processing/regex/regex_tagger.py
> +        # ----------------------- 1 -----------------------------#
+1

2018-01-22 18:21 UTC, dodoels commented on src/ml_service/model_training/training_driver.py
> +    if CommandEnum.SIMILARITY_FINDER in command_list:
From the abstract point of view for better project structure since we are using the model to predict/search for data, we should have `similar_finder` in a different directory such as `controller` or `service`. It doesn't really `train` the model. This is to avoid technical debt in the future.

2018-01-22 18:23 UTC, Taimoorrana1 commented
Fixed a crash due to one of the of regexes. Still reviewing

2018-01-22 18:26 UTC, arekmano requested changes

2018-01-22 18:26 UTC, arekmano commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +                r"\(?\K" + MONEY_REGEX + r"\)?",
The MONEY_REGEX should not be optional. Or else, we will match the regex, but not have a $$ amount obtained with it.

2018-01-22 18:26 UTC, arekmano commented
Minor issue with regex.

2018-01-22 18:27 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +                r"\(?\K" + MONEY_REGEX + r"\)?",
the parentheses are optional

2018-01-22 18:42 UTC, Taimoorrana1 commented
Looks good to me

2018-01-22 18:43 UTC, TaimoorRana approved these changes

2018-01-22 18:54 UTC, Samuel-Campbell commented on src/ml_service/model_training/training_driver.py
> +    if CommandEnum.SIMILARITY_FINDER in command_list:
yes it does train a model

2018-01-22 19:12 UTC, arekmano commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +                r"\(?\K" + MONEY_REGEX + r"\)?",
my bad. i thought it was (abc)? instead of \(?abc\)?

2018-01-22 19:12 UTC, arekmano approved these changes

2018-01-22 20:20 UTC, merged