251/date regexes
Cyberjusticelab/JusticeAI pull request #294
Opened 2018-01-22 07:23 UTC by Taimoorrana1

NOT READY TO MERGE

Added Date regexes
Added Entity Extraction for Date

Missing:
Date to Unix time

2018-01-22 18:28 UTC, dodoels commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +    month_dict = {'janvier': 1, 'février': 2, 'mars': 3, 'avril': 4, 'mai': 5, 'juin': 6,
Is it possible to extract such month dict from pyEnchant? just for more generic implementation instead of hard-coded strings.

2018-01-22 18:45 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +    month_dict = {'janvier': 1, 'février': 2, 'mars': 3, 'avril': 4, 'mai': 5, 'juin': 6,
yes, I will look if it's possible. it should be.

2018-01-22 19:09 UTC, arekmano commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +    month_dict = {'janvier': 1, 'février': 2, 'mars': 3, 'avril': 4, 'mai': 5, 'juin': 6,
IMO it is easier to hard-code the string. PyEnchant does not offer such functionality.

2018-01-22 19:10 UTC, arekmano commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +    month_dict = {'janvier': 1, 'février': 2, 'mars': 3, 'avril': 4, 'mai': 5, 'juin': 6,
Howerver, I think that the matches should be case-insensitive and resistant to mistakes

2018-01-22 22:13 UTC, Samuel-Campbell submitted a review, later dismissed
Add unittest for dates

2018-01-22 22:43 UTC, Taimoorrana1 commented
@Samuel-Campbell I will be adding them. It's not ready to be merged

2018-01-24 00:44 UTC, Samuel-Campbell approved these changes

2018-01-24 00:44 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[2] = date_components[2]
what is this line for?

2018-01-24 00:46 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[2] = date_components[2]
good catch. it's a mistake while I was testing some code. fixing

2018-01-24 00:48 UTC, arekmano commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +    month_dict = {'janvier': 1, 'février': 2, 'mars': 3, 'avril': 4, 'mai': 5, 'juin': 6,
these should also catch months without accents, i.e. fevrier (some OCR has failed in certain cases)

2018-01-24 00:49 UTC, arekmano commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
what about accented e's?

2018-01-24 00:50 UTC, arekmano approved these changes
Minor changes, not blockers however.

2018-01-24 00:50 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
example?

2018-01-24 00:52 UTC, mihaiqc commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
"er|ère|ème|em" unless for some reason they decided not to put accents in the cases.

Also not sure when "em" and "ere" are ever used.

2018-01-24 00:54 UTC, ghost requested changes

2018-01-24 00:54 UTC, mihaiqc commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
"er|ère|ème|em" unless for some reason they decided not to put accents in the cases.

Also not sure when "em" and "ere" are ever used but that one is not too important as those two will probably just not  get picked up.

2018-01-24 00:54 UTC, mihaiqc commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction_test.py
> +                r"l'indemnité additionnelle prévue à l'article 1619 C\.c\.Q\., à compter du \K(?i)\d{1,2}(er|ere|em|eme)? \w{3,9} \d{4}",
same as last comment

2018-01-24 00:57 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
Found many with 'ere|eme' . I will add with accents as well, to be on the safe side

2018-01-24 01:02 UTC, mihaiqc commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
That's very strange... not proper French I guess.

2018-01-24 01:05 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
got what you meant. it's what @mihaiqc pointed out as well

2018-01-24 01:42 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
@mihaiqc I am now removing accents from the sentence before doing any matching. Please review

2018-01-24 02:11 UTC, mihaiqc commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
I think that would take more processing power than adding an extra accent but what works works.

2018-01-24 02:12 UTC, ghost approved these changes

2018-01-24 02:22 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_entity_extraction.py
> +                date_components[0] = re.sub(r"er|ere|em|eme", "", date_components[0])
I did that because months also need a non-accent version, which would require me to change more code than necessary. This solve both issues

2018-01-24 02:22 UTC, merged