251/regression
Cyberjusticelab/JusticeAI pull request #300
Opened 2018-01-23 20:35 UTC by Samuel-Campbell

1) Finished regressoin
2) made unittests
3) tested on sample size of 100

2018-01-23 21:20 UTC, arekmano requested changes

2018-01-23 21:20 UTC, arekmano commented on src/ml_service/model_training/regression/multi_class_svr.py
> +        r_Score = r2_score(y_test, y_predict)
it makes more sense to have an R2 score and explained variance per regressor, (i.e. per outcome predicted) rather than the overall score, as we can identify which outcomes are having difficulties with a particular regressor.

2018-01-23 21:20 UTC, arekmano commented on src/ml_service/model_training/regression/multi_class_svr.py
> +        self.data_set = data_set
since the dataset is huge, doing this would make the MultiClassSVR instance unnecessarily large, either train in the constructor, or clear the dataset field after the training is complete.

2018-01-23 21:20 UTC, arekmano commented on src/ml_service/model_training/regression/multi_class_svr.py
> +    def reshape_dataset(self):
make this a private method? (non-blocker)

2018-01-23 21:20 UTC, arekmano commented on src/ml_service/model_training/regression/multi_class_svr.py
> +        clf = MultiOutputRegressor(SVR(kernel='linear')) # 3
There should add a method similar to SVM#evaluate_best_parameters, to brute force the best possible kernel, C, and epsilon parameters of the SVR. This would help us isolate the best parameters for our dataset. Additionally, using MultiOutputRegressor will cause all predictions to be given by the same estimator, which will not give the most optimal outcome.

I.e. additional_indemnity_outcome and tenant_ordered_to_pay_landlord may have better results with "linear" and "poly" kernels respectively

2018-01-23 21:20 UTC, arekmano commented on src/ml_service/model_training/regression/multi_class_svr.py
> +        clf = MultiOutputRegressor(SVR(kernel='linear')) # 3
this is a non-blocker but a code change will have to be made if we want to present good results to the PO

2018-01-23 23:15 UTC, Samuel-Campbell commented on src/ml_service/model_training/regression/multi_class_svr.py
> +        clf = MultiOutputRegressor(SVR(kernel='linear')) # 3
No read this:
scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html

MultiOutputRegressor generates a different formula for each column

2018-01-23 23:23 UTC, arekmano commented on src/ml_service/model_training/regression/multi_class_svr.py
> +        clf = MultiOutputRegressor(SVR(kernel='linear')) # 3
explained further in slack

2018-01-24 00:34 UTC, arekmano approved these changes
lgtm

2018-01-24 00:59 UTC, merged