[#186] regex clean up - NOT READY TO MERGE
Cyberjusticelab/JusticeAI pull request #330
Opened 2018-02-05 00:05 UTC by Taimoorrana1

**Regexes removed:**

- Absent 
- incorrect_facts 
- landlord_rent_change_piece_justification
- proof_of_revenu
- lack_of_proof
- tenant_landlord_agreement 
- tenant_negligence
- tenant_not_request_cancel_lease
- tenant_rent_paid_before_hearing 

**Regexes renamed** 
lease => 'tenant_lease_fixed'
proof_of_late => ‘signed_proof_of_rent_debt’
apartment_impropre => appartment_dirty

**Regexes merges** 
Merged apartment_infestation in apartment_dirty

**Regexes Fix/added**
apartment_infestation
Violent

**Precedents removed:**

4858 precedents removed due to following regexes

- Absent
- incorrect_facts
- tenant_landlord_agreement
- tenant_rent_paid_before_hearing 

109 English precedents removed

Total removed **4967**

2018-02-05 23:47 UTC, arekmano requested changes
Can you paste the results of running the regex parsing?

2018-02-06 01:04 UTC, Taimoorrana1 commented
INFO: Total precedents parsed: 40003
INFO: Total precedents with apartment_dirty                           : 743
INFO: Total precedents with asker_is_landlord                         : 28881
INFO: Total precedents with asker_is_tenant                           : 2351
INFO: Total precedents with bothers_others                            : 3
INFO: Total precedents with case_fee_reimbursement                    : 139
INFO: Total precedents with disrespect_previous_judgement             : 123
INFO: Total precedents with landlord_inspector_fees                   : 475
INFO: Total precedents with landlord_notifies_tenant_retake_apartment : 376
INFO: Total precedents with landlord_pays_indemnity                   : 40
INFO: Total precedents with landlord_prejudice_justified              : 17733
INFO: Total precedents with landlord_relocation_indemnity_fees        : 508
INFO: Total precedents with landlord_rent_change                      : 2376
INFO: Total precedents with landlord_rent_change_doc_renseignements   : 310
INFO: Total precedents with landlord_retakes_apartment                : 1578
INFO: Total precedents with landlord_retakes_apartment_indemnity      : 94
INFO: Total precedents with landlord_sends_demand_regie_logement      : 546
INFO: Total precedents with tenant_lease_fixed                        : 24919
INFO: Total precedents with signed_proof_of_rent_debt                 : 29
INFO: Total precedents with rent_increased                            : 1
INFO: Total precedents with tenant_bad_payment_habits                 : 28155
INFO: Total precedents with tenant_continuous_late_payment            : 4027
INFO: Total precedents with tenant_damaged_rental                     : 19
INFO: Total precedents with tenant_dead                               : 31
INFO: Total precedents with tenant_financial_problem                  : 299
INFO: Total precedents with tenant_group_responsability               : 1256
INFO: Total precedents with tenant_individual_responsability          : 3779
INFO: Total precedents with tenant_is_bothered                        : 25
INFO: Total precedents with tenant_lease_fixed                        : 24919
INFO: Total precedents with tenant_lease_indeterminate                : 1129
INFO: Total precedents with tenant_left_without_paying                : 7078
INFO: Total precedents with tenant_monthly_payment                    : 34112
INFO: Total precedents with tenant_owes_rent                          : 21839
INFO: Total precedents with tenant_refuses_retake_apartment           : 130
INFO: Total precedents with tenant_rent_not_paid_less_3_weeks         : 1675
INFO: Total precedents with tenant_rent_not_paid_more_3_weeks         : 20523
INFO: Total precedents with tenant_withold_rent_without_permission    : 80
INFO: Total precedents with violent                                   : 471
INFO: Total precedents with not_violent                               : 52
INFO: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO: Total precedents with demand_lease_modification                 : 6
INFO: Total precedents with demand_resiliation                        : 25998
INFO: Total precedents with landlord_claim_interest_damage            : 1591
INFO: Total precedents with landlord_demand_access_rental             : 147
INFO: Total precedents with landlord_demand_bank_fee                  : 38
INFO: Total precedents with landlord_demand_damage                    : 3513
INFO: Total precedents with landlord_demand_legal_fees                : 3747
INFO: Total precedents with landlord_demand_retake_apartment          : 369
INFO: Total precedents with landlord_demand_utility_fee               : 204
INFO: Total precedents with landlord_fix_rent                         : 2413
INFO: Total precedents with landlord_lease_termination                : 23357
INFO: Total precedents with landlord_money_cover_rent                 : 15420
INFO: Total precedents with paid_judicial_fees                        : 3533
INFO: Total precedents with tenant_claims_harassment                  : 41
INFO: Total precedents with tenant_cover_rent                         : 23331
INFO: Total precedents with tenant_demands_decision_retraction        : 973
INFO: Total precedents with tenant_demand_indemnity_Code_Civil        : 219
INFO: Total precedents with tenant_demand_indemnity_damage            : 4271
INFO: Total precedents with tenant_demand_indemnity_judicial_fee      : 22
INFO: Total precedents with tenant_demand_interest_damage             : 736
INFO: Total precedents with tenant_demands_money                      : 1830
INFO: Total precedents with tenant_demand_rent_decrease               : 828
INFO: Total precedents with tenant_respect_of_contract                : 18
INFO: Total precedents with tenant_eviction                           : 21883
INFO: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO: Total precedents with additional_indemnity_date                 : 21593
INFO: Total precedents with additional_indemnity_money                : 13676
INFO: Total precedents with declares_housing_inhabitable              : 16
INFO: Total precedents with declares_resiliation_is_correct           : 5477
INFO: Total precedents with landlord_serious_prejudice                : 113
INFO: Total precedents with orders_expulsion                          : 19201
INFO: Total precedents with orders_immediate_execution                : 13308
INFO: Total precedents with orders_resiliation                        : 19831
INFO: Total precedents with orders_tenant_pay_first_of_month          : 240
INFO: Total precedents with rejects_landlord_demand                   : 930
INFO: Total precedents with rejects_tenant_demand                     : 935
INFO: Total precedents with tenant_ordered_to_pay_landlord            : 17746
INFO: Total precedents with tenant_ordered_to_pay_landlord_legal_fees : 15028

2018-02-06 01:27 UTC, Samuel-Campbell commented
For sure wrong:
rent_increased : 1

remove:
INFO: Total precedents with rejects_landlord_demand : 930
INFO: Total precedents with rejects_tenant_demand : 935

2018-02-06 23:01 UTC, arekmano commented on src/ml_service/util/precendent_directory_cleaner.py
> +FACT_DIGIT_REGEX = r"\[\d+\]"
can we remove FACT_DIGIT_REGEX as part of this PR? it doesn't catch facts where there is a newline between the digit and the text

2018-02-06 23:04 UTC, Samuel-Campbell commented on src/ml_service/util/precendent_directory_cleaner.py
> +FACT_DIGIT_REGEX = r"\[\d+\]"
i did it already but for some reason my changes aren't showing up

2018-02-07 01:59 UTC, Samuel-Campbell commented
INFO: Total precedents parsed: 40003
INFO: Total precedents with apartment_dirty                           : 882
INFO: Total precedents with asker_is_landlord                         : 29606
INFO: Total precedents with asker_is_tenant                           : 2699
INFO: Total precedents with bothers_others                            : 40
INFO: Total precedents with disrespect_previous_judgement             : 126
INFO: Total precedents with landlord_inspector_fees                   : 504
INFO: Total precedents with landlord_notifies_tenant_retake_apartment : 437
INFO: Total precedents with landlord_pays_indemnity                   : 47
INFO: Total precedents with landlord_relocation_indemnity_fees        : 513
INFO: Total precedents with landlord_rent_change                      : 2420
INFO: Total precedents with landlord_rent_change_doc_renseignements   : 310
INFO: Total precedents with landlord_retakes_apartment                : 1722
INFO: Total precedents with landlord_sends_demand_regie_logement      : 132
INFO: Total precedents with tenant_sends_demand_regie_logement        : 1
INFO: Total precedents with tenant_lease_fixed                        : 24942
INFO: Total precedents with signed_proof_of_rent_debt                 : 29
INFO: Total precedents with rent_increased                            : 1426
INFO: Total precedents with tenant_continuous_late_payment            : 4063
INFO: Total precedents with tenant_damaged_rental                     : 694
INFO: Total precedents with tenant_dead                               : 31
INFO: Total precedents with tenant_financial_problem                  : 307
INFO: Total precedents with tenant_group_responsability               : 1256
INFO: Total precedents with tenant_individual_responsability          : 3780
INFO: Total precedents with tenant_is_bothered                        : 26
INFO: Total precedents with tenant_lease_fixed                        : 24942
INFO: Total precedents with tenant_lease_indeterminate                : 1405
INFO: Total precedents with tenant_left_without_paying                : 7115
INFO: Total precedents with tenant_monthly_payment                    : 34192
INFO: Total precedents with tenant_owes_rent                          : 21902
INFO: Total precedents with tenant_refuses_retake_apartment           : 409
INFO: Total precedents with tenant_rent_not_paid_less_3_weeks         : 1691
INFO: Total precedents with tenant_rent_not_paid_more_3_weeks         : 20734
INFO: Total precedents with tenant_withold_rent_without_permission    : 90
INFO: Total precedents with violent                                   : 594
INFO: Total precedents with not_violent                               : 65
INFO: Total precedents with tenant_not_paid_lease_timespan            : 112
INFO: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO: Total precedents with demand_lease_modification                 : 6
INFO: Total precedents with demand_resiliation                        : 26195
INFO: Total precedents with landlord_claim_interest_damage            : 1747
INFO: Total precedents with landlord_demand_access_rental             : 458
INFO: Total precedents with landlord_demand_bank_fee                  : 40
INFO: Total precedents with landlord_demand_damage                    : 3811
INFO: Total precedents with landlord_demand_legal_fees                : 3819
INFO: Total precedents with landlord_demand_retake_apartment          : 381
INFO: Total precedents with landlord_demand_utility_fee               : 587
INFO: Total precedents with landlord_fix_rent                         : 2503
INFO: Total precedents with landlord_lease_termination                : 24099
INFO: Total precedents with landlord_money_cover_rent                 : 15500
INFO: Total precedents with paid_judicial_fees                        : 3595
INFO: Total precedents with tenant_claims_harassment                  : 64
INFO: Total precedents with tenant_cover_rent                         : 23478
INFO: Total precedents with tenant_demands_decision_retraction        : 1020
INFO: Total precedents with tenant_demand_indemnity_Code_Civil        : 439
INFO: Total precedents with tenant_demand_indemnity_damage            : 30430
INFO: Total precedents with tenant_demand_indemnity_judicial_fee      : 22
INFO: Total precedents with tenant_demand_interest_damage             : 951
INFO: Total precedents with tenant_demands_money                      : 2667
INFO: Total precedents with tenant_demand_rent_decrease               : 1146
INFO: Total precedents with tenant_respect_of_contract                : 19
INFO: Total precedents with case_fee_reimbursement                    : 142
INFO: Total precedents with tenant_eviction                           : 22152
INFO: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO: Total precedents with additional_indemnity_money                : 13674
INFO: Total precedents with declares_housing_inhabitable              : 16
INFO: Total precedents with declares_resiliation_is_correct           : 5477
INFO: Total precedents with landlord_serious_prejudice                : 2508
INFO: Total precedents with orders_expulsion                          : 19201
INFO: Total precedents with orders_immediate_execution                : 13308
INFO: Total precedents with orders_resiliation                        : 19831
INFO: Total precedents with orders_tenant_pay_first_of_month          : 240
INFO: Total precedents with tenant_ordered_to_pay_landlord            : 17746
INFO: Total precedents with tenant_ordered_to_pay_landlord_legal_fees : 15028
INFO: Total precedents with landlord_prejudice_justified              : 18320
INFO: Total precedents with landlord_retakes_apartment_indemnity      : 100
INFO: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

2018-02-08 15:58 UTC, arekmano requested changes
Please remove binaries and add to CJL server

2018-02-08 16:00 UTC, dodoels approved these changes
LGTM

2018-02-08 16:00 UTC, choitwao commented on src/ml_service/feature_extraction/clustering/clustering_driver_test.py
> +        __rel_path = r'data/test/mock_precedent/'
it is easier to just add this path to `Path`

2018-02-08 16:04 UTC, Samuel-Campbell commented
INFO: Column: declares_housing_inhabitable
INFO: Test accuracy: 99.96250468691413%
INFO: Precision: [ 0.99962505  0.        ]
INFO: Recall: [ 1.  0.]
INFO: F1: [ 0.99981249  0.        ]

INFO: Column: declares_resiliation_is_correct
INFO: Test accuracy: 92.00099987501562%
INFO: Precision: [ 0.95488831  0.70280036]
INFO: Recall: [ 0.95240162  0.7144169 ]
INFO: F1: [ 0.95364334  0.70856102]

INFO: Column: landlord_serious_prejudice
INFO: Test accuracy: 96.7504061992251%
INFO: Precision: [ 0.99373126  0.67722474]
INFO: Recall: [ 0.97148948  0.90707071]
INFO: F1: [ 0.98248451  0.77547496]

INFO: Column: orders_expulsion
INFO: Test accuracy: 95.0631171103612%
INFO: Precision: [ 0.95154713  0.94963466]
INFO: Recall: [ 0.95360577  0.94740953]
INFO: F1: [ 0.95257534  0.94852079]

INFO: Column: orders_immediate_execution
INFO: Test accuracy: 87.1016122984627%
INFO: Precision: [ 0.92142283  0.78809917]
INFO: Recall: [ 0.87734405  0.8590991 ]
INFO: F1: [ 0.89884336  0.82206897]

INFO: Column: orders_resiliation
INFO: Test accuracy: 96.58792650918635%
INFO: Precision: [ 0.95058767  0.98251566]
INFO: Recall: [ 0.98337469  0.9481239 ]
INFO: F1: [ 0.96670326  0.96501346]

INFO: Column: orders_tenant_pay_first_of_month
INFO: Test accuracy: 98.38770153730783%
INFO: Precision: [ 0.98387702  0.        ]
INFO: Recall: [ 1.  0.]
INFO: F1: [ 0.99187299  0.        ]

INFO: Column: tenant_ordered_to_pay_landlord
INFO: Test accuracy: 84.01449818772653%
INFO: Precision: [ 0.79281184  0.8600071 ]
INFO: Recall: [ 0.70382883  0.90818812]
INFO: F1: [ 0.74567508  0.88344117]

INFO: Column: tenant_ordered_to_pay_landlord_legal_fees
INFO: Test accuracy: 89.98875140607424%
INFO: Precision: [ 0.88865368  0.90459301]
INFO: Recall: [ 0.79598028  0.95096943]
INFO: F1: [ 0.83976795  0.92720167]

INFO: Column: landlord_prejudice_justified
INFO: Test accuracy: 80.16497937757781%
INFO: Precision: [ 0.82326986  0.77645467]
INFO: Recall: [ 0.81102722  0.79035813]
INFO: F1: [ 0.81710269  0.78334471]

INFO: Column: landlord_retakes_apartment_indemnity
INFO: Test accuracy: 99.76252968378952%
INFO: Precision: [ 0.9976253  0.       ]
INFO: Recall: [ 1.  0.]
INFO: F1: [ 0.99881124  0.        ]

INFO: Column: orders_landlord_notify_tenant_when_habitable
INFO: Test accuracy: 100.0%
INFO: Precision: [ 1.]
INFO: Recall: [ 1.]
INFO: F1: [ 1.]

INFO: Column: authorize_landlord_retake_apartment
INFO: Test accuracy: 99.4750656167979%
INFO: Precision: [ 0.99635907  0.63888889]
INFO: Recall: [ 0.99836457  0.44230769]
INFO: F1: [ 0.99736081  0.52272727]

2018-02-08 16:06 UTC, arekmano requested changes

2018-02-08 16:06 UTC, arekmano commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +        ("landlord_retakes_apartment", [
This will also catch Outcomes i.e. AUTORISE le locateur de reprendre le logement

2018-02-08 16:06 UTC, arekmano commented on src/ml_service/feature_extraction/pre_processing/filter_precedent/precendent_directory_cleaner.py
> +import os
Can you post the cleaned version of dataset to CJL server?

2018-02-08 16:08 UTC, arekmano commented on src/ml_service/feature_extraction/pre_processing/filter_precedent/precendent_directory_cleaner.py
> +import os
Either that, or update README with cleaning command.

2018-02-08 17:13 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/pre_processing/filter_precedent/precendent_directory_cleaner.py
> +import os
I updated the pre-processing step

2018-02-08 17:14 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +        ("landlord_retakes_apartment", [
unittest this in another PR. I can't test ALL of them

2018-02-08 17:16 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib_test.py
> +        sentences = [
These tests are too small to validate a regex. We should be adding way more sentences. I would say at least 30+ sentences

2018-02-08 17:17 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib_test.py
> +        sentences = [
this is a proof of concept. but these are the sort of tests we need

2018-02-08 17:18 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/clustering/clustering_driver_test.py
> +        __rel_path = r'data/test/mock_precedent/'
something was not working well in the unittest so i added this manually

2018-02-08 17:20 UTC, Taimoorrana1 commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib_test.py
> +        sentences = [
since we are going to add a lot of sentences, it will clutter the tests. It would be better to have a file for each regex that contains all the sentences the needs to be tested.

2018-02-08 17:32 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib_test.py
> +        sentences = [
you can refactor it however you want in another PR

2018-02-08 18:03 UTC, arekmano approved these changes
Looks good now

2018-02-08 19:41 UTC, merged