[#186] Added regex for Retaking rental outcome
Cyberjusticelab/JusticeAI pull request #337
Opened 2018-02-06 23:23 UTC by arekmano

2018-02-06 23:53 UTC, dodoels approved these changes
LGTM

2018-02-07 00:22 UTC, Samuel-Campbell requested changes
no more regex without unittest. It;s a complete disaster atm

2018-02-07 17:36 UTC, Samuel-Campbell commented
close PR this is done already

2018-02-07 17:40 UTC, mihaiqc commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +                r"AUTORISE (le|la|les) " + LANDLORD_REGEX + r" à reprendre (possession )?(du|le|des|de leur|de son) (logement|lieux)",
They only use logement et lieux?
habitation, apartment, demeure, résidence, domicile, logis, maison, studio, habitat
are never seen? Just worried this might not capture everything

2018-02-07 17:42 UTC, ghost approved these changes

2018-02-08 16:08 UTC, choitwao commented
I am closing this PR. PR #330 includes this regex in refactored form.

2018-02-08 16:08 UTC, closed without merging