[#25] Proper integration of OCR with service API, with meaningful image data.
Cyberjusticelab/JusticeAI pull request #340
Opened 2018-02-07 16:11 UTC by lancelafontaine

[#25] 

- [x] Integrates proper image data decoding into API with base64-encoded png data that would be sent from front-end

2018-02-07 16:18 UTC, Vynny requested changes

2018-02-07 16:18 UTC, Vynny commented on src/task_service/README.md
> +    "image_data": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAqcAAADACAIAAAC26V2YAAA3/0lEQVR4nO3dLZTi2Noo4Hfu+tYKLrmKfOIuclRyFTnrCjiKjLkw5sJRMApGwVEwCsaVg1EwClrBKGgFraAVaUVakVKkFSlFSpFSBJUrwk8CCX
This isn't good practice at all. Base64 can significantly increase the size of even a small image. Why simply take the code we have for uploading the lease on the backend and use that here?

2018-02-07 17:36 UTC, lancelafontaine commented on src/task_service/README.md
> +    "image_data": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAqcAAADACAIAAAC26V2YAAA3/0lEQVR4nO3dLZTi2Noo4Hfu+tYKLrmKfOIuclRyFTnrCjiKjLkw5sJRMApGwVEwCsaVg1EwClrBKGgFraAVaUVakVKkFSlFSpFSBJUrwk8CCX
As far as I'm aware, representing image data in base64 is pretty standard on the frontend. Placing ☝️ in `<img src="..." /> displays the image.

You're right about using whatever functionality backend has though.

2018-02-07 17:44 UTC, Vynny commented on src/task_service/README.md
> +    "image_data": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAqcAAADACAIAAAC26V2YAAA3/0lEQVR4nO3dLZTi2Noo4Hfu+tYKLrmKfOIuclRyFTnrCjiKjLkw5sJRMApGwVEwCsaVg1EwClrBKGgFraAVaUVakVKkFSlFSpFSBJUrwk8CCX
Representing thumbnails and other small images in base64 is standard, not large images.
In any case, just rip the file upload stuff from backend and use multipart upload for the ocr, makes it easier to set stuff like file upload limits and specify filetype support.

2018-02-08 16:07 UTC, choitwao commented on src/task_service/README.md
> +    "image_data": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAqcAAADACAIAAAC26V2YAAA3/0lEQVR4nO3dLZTi2Noo4Hfu+tYKLrmKfOIuclRyFTnrCjiKjLkw5sJRMApGwVEwCsaVg1EwClrBKGgFraAVaUVakVKkFSlFSpFSBJUrwk8CCX
I agree with Vynny, usually you only base64 the small images

2018-02-08 23:33 UTC, closed without merging