[#345] Removes Docker images and database on every deploy
Cyberjusticelab/JusticeAI pull request #359
Opened 2018-02-23 14:29 UTC by lancelafontaine

[#345]

- [x] Modify `cjl` script to accept `-y` flags to prevent input prompt on the `clean` and `reset-db` commands.
- [x] Applies both modified `cjl` commands to continous deployment strategy

2018-02-23 14:31 UTC, lancelafontaine commented
Since each service is running in Travis as it's own job in parallel, we may need some kind of homemade semaphore that make sure that this only happens once, for the last job to be completed. May require a future PR once this one is merged.

2018-02-23 14:38 UTC, dodoels approved these changes

2018-02-23 17:35 UTC, Vynny approved these changes

2018-02-25 03:57 UTC, arekmano requested changes

2018-02-25 03:57 UTC, arekmano commented on cjl
> +      clean
why call it 2x?

2018-02-25 03:57 UTC, arekmano commented on cjl
> +      clean
same as above

2018-02-25 15:47 UTC, lancelafontaine commented on cjl
> +      clean
Probably not needed, but I've sometimes some situations where more images get removed if you do it a second time, I think in cases when there are "nested images" (?). Regardless, no harm in running it twice, and our script should try to enforce the state we want.

2018-02-25 18:40 UTC, arekmano approved these changes
ok

2018-02-25 18:41 UTC, merged