8/api endpoints
Cyberjusticelab/JusticeAI pull request #41
Opened 2017-10-08 15:50 UTC by arekmano

- Created classifiers for tenant/landlord and problem categories
- Added new endpoints
- Updated docker build process for this container

2017-10-08 15:53 UTC, lancelafontaine commented on src/nlp_service/models/question.py
> +    """docstring for Question"""
Don't seem very useful for now

2017-10-08 15:55 UTC, lancelafontaine approved these changes
Looks good to me, but you should update your branch with changes from master.

2017-10-08 16:03 UTC, arekmano commented
updated from master

2017-10-08 16:04 UTC, arekmano commented
I'd like @Vynny, @mihaiqc or @Samuel-Campbell to take a look at the changes as this will impact their work.

2017-10-08 17:44 UTC, Vynny requested changes

2017-10-08 17:44 UTC, Vynny commented on src/nlp_service/services/introduction_parser.py
> +            'Jackie Chan',
This should be the person's name

2017-10-09 03:16 UTC, Samuel-Campbell commented
Only comment I have is that I notice you don't use encapsulation. Other than that looks fine

2017-10-09 14:19 UTC, arekmano commented on src/nlp_service/services/introduction_parser.py
> +            'Jackie Chan',
This functionality isn't implemented yet. It returns a static string until we figure it out.

2017-10-09 14:21 UTC, arekmano commented
I didn't use encapsulation because it is easier to debug this way.

2017-10-09 16:19 UTC, Samuel-Campbell approved these changes

2017-10-09 17:25 UTC, Vynny approved these changes

2017-10-12 00:25 UTC, merged