#401 date regex fix
Cyberjusticelab/JusticeAI pull request #419
Opened 2018-03-27 22:19 UTC by TaimoorRana

Added/updated regexes for dates

2018-03-27 23:18 UTC, Samuel-Campbell requested changes
Regex will catch too many irrelevant things

2018-03-27 23:18 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +    DATE_RANGE_REGEX = r"(?i)(\d{1,2})?(?:er|èr|ere|em|eme|ème)?\s?(\w{3,9}) (\d{4})?\s?" \
careful. We don't want the time of the lease but the time for which a tenant hasn't paid.

2018-03-28 00:50 UTC, TaimoorRana commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +    DATE_RANGE_REGEX = r"(?i)(\d{1,2})?(?:er|èr|ere|em|eme|ème)?\s?(\w{3,9}) (\d{4})?\s?" \
Oh, I didn't know we needed it specifically for that. I'll change it

2018-03-28 15:52 UTC, Samuel-Campbell commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +    DATE_RANGE_REGEX = r"(?i)(\d{1,2})?(?:er|èr|ere|em|eme|ème)?\s?(\w{3,9}) (\d{4})?\s?" \
its possible we don't even need the regex after thinking about it. Check ml channel

2018-03-28 15:53 UTC, TaimoorRana commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +    DATE_RANGE_REGEX = r"(?i)(\d{1,2})?(?:er|èr|ere|em|eme|ème)?\s?(\w{3,9}) (\d{4})?\s?" \
I saw the channel but this way almost done, so I finished it.

2018-03-28 15:54 UTC, TaimoorRana commented on src/ml_service/feature_extraction/post_processing/regex/regex_lib.py
> +    DATE_RANGE_REGEX = r"(?i)(\d{1,2})?(?:er|èr|ere|em|eme|ème)?\s?(\w{3,9}) (\d{4})?\s?" \
if we ever need it, it will be there.

2018-03-28 16:26 UTC, Samuel-Campbell approved these changes
can you tag precedents and upload model to CJL when you got time?

2018-03-28 16:31 UTC, TaimoorRana commented
sure

2018-03-28 16:31 UTC, merged