[#4] Adds volumes to development environment for autoreload, etc
Cyberjusticelab/JusticeAI pull request #52
Opened 2017-10-10 13:05 UTC by lancelafontaine

[#4]

-[x] Adds volumes to development environment for autoreload, etc.

I can confirm that the volumes actually work. The `web_client` service is able to develop and autoreload the latest changes. However, autoreload does not seem to be working for the Flask services. I added the `DEBUG=1` environment variable like the documentation says, but still no autoreload. That is something that we will have to revisit later.

2017-10-10 15:42 UTC, dodoels approved these changes

2017-10-10 20:22 UTC, arekmano requested changes
copy command

2017-10-10 20:22 UTC, arekmano commented on docker-compose.dev.yml
> +      - ./src/ml_service:/usr/src/app
we should remove the COPY command from the Dockerfiles in this case.

2017-10-10 21:01 UTC, lancelafontaine commented on docker-compose.dev.yml
> +      - ./src/ml_service:/usr/src/app
I don't want to make multiple different Dockerfiles for different environments though. Purpose was to keep everything identical except for the `docker-compose.dev.yml` file. @arekmano

2017-10-11 00:29 UTC, arekmano commented on docker-compose.dev.yml
> +      - ./src/ml_service:/usr/src/app
we're technically now copying and then overriding contents of folder with volumes. ohwell

2017-10-11 00:29 UTC, arekmano approved these changes

2017-10-11 00:31 UTC, lancelafontaine commented on docker-compose.dev.yml
> +      - ./src/ml_service:/usr/src/app
Yeah, I agree it's not the best, although I think it's an acceptable tradeoff for the reduced complexity.

2017-10-11 00:31 UTC, merged