15/chat ui and functional interaction
Cyberjusticelab/JusticeAI pull request #55
Opened 2017-10-12 04:27 UTC by choitwao

- [ ] Removed old POC UI and codes
- [ ] Structured a bit of webpack and framework file structure for better coding experience :)
- [ ] Integrated bunch of libraries (slider, bootstrap, resource, localstorage etc.)
- [ ] Create basic UI for chat component without any fancy layout since our UI mockup is not yet ready
- [ ] Create logic for the chat component 
- [ ] Integrate with backend service with rest calls, and handle/bind all the data on frontend
- [ ] Test the functionality and integration
- [ ] Create unit test

2017-10-12 23:24 UTC, arekmano commented
Can you post screenshots whenever there is a UI change? It is easier to code review

2017-10-13 00:29 UTC, choitwao commented
![image](https://user-images.githubusercontent.com/12192439/31525104-f49c4abe-af8b-11e7-8fb5-104277029307.png)
There is no theme just a functional component. By the time the UI/theme is ready we are need to do is assemble them on the page and css it.

2017-10-13 05:00 UTC, arekmano approved these changes
...

2017-10-13 05:02 UTC, arekmano requested changes
How come there is no theme? We had discussed that we would design an initial theme? Product Owner will have expectations about the UI that will not be met tomorrow...

2017-10-13 18:40 UTC, arekmano approved these changes

2017-10-14 09:56 UTC, choitwao commented
![image](https://user-images.githubusercontent.com/12192439/31574771-3817b8c8-b0a4-11e7-80e4-d5e5f530323b.png)
Initial UI on PC
![image](https://user-images.githubusercontent.com/12192439/31574779-47ede880-b0a4-11e7-80e6-069c016d96b2.png)
Initial UI on iPad
![image](https://user-images.githubusercontent.com/12192439/31574782-5201d6e2-b0a4-11e7-8d8e-c4e97895684d.png)
Initial UI on IPhone

2017-10-14 10:12 UTC, merged