[#5] Adds addditional prompt for disclaimer acceptance with related functionality
Cyberjusticelab/JusticeAI pull request #98
Opened 2017-10-26 14:22 UTC by lancelafontaine

[#5]

- Adds a disclaimer prompt to the conversation between bot and user.
- Populates response with related information (`additional_info`, `possible_answers`)

Next steps:
- [ ] Front-end: disable text input, display answer buttons
- [ ] Front-end: parse message for disclaimer as HTML based on `additional_info.should_parse_as_html`
- [ ] Front-end: Create legal page which fetches entire legal text from backend and displays it
- [ ] Backend: Create a `GET /legal` endpoint which stores and versions legal documents.

2017-10-26 16:14 UTC, Vynny commented on src/backend_service/controllers/conversationController.py
> +        possible_answers = ["Yes"]
Shouldn't there be a "No" answer?

2017-10-26 16:17 UTC, lancelafontaine commented on src/backend_service/controllers/conversationController.py
> +        possible_answers = ["Yes"]
A couple of us discussed this a bit, and felt like if the user absolutely disagreed with the disclaimer, they could just not use the service, or close the browser tab.

2017-10-26 17:36 UTC, arekmano commented
Good initial implementation

2017-10-26 19:35 UTC, Taimoorrana1 commented on src/backend_service/services/staticStrings.py
> +        "Hello {name}! Before we start, I want make it clear that I am not a replacement for a lawyer and any information I provide you with is not meant to be construed as legal advice. Always check
I want to*

2017-10-26 19:39 UTC, Taimoorrana1 commented on src/backend_service/controllers/conversationController.py
> +        additional_info = {"should_parse_as_html": True}
just curious, what are we parsing as HTML?

2017-10-26 19:41 UTC, lancelafontaine commented on src/backend_service/controllers/conversationController.py
> +        additional_info = {"should_parse_as_html": True}
We should parse the disclaimer text as HTML, because it will contain an HTML link to a legal page.

2017-10-26 19:41 UTC, Taimoorrana1 commented on src/backend_service/controllers/conversationController.py
> +    if len(conversation.messages) <= 2:
Why is 2 being used?  what does 2 represent?

2017-10-26 19:50 UTC, Vynny commented on src/backend_service/controllers/conversationController.py
> +    if len(conversation.messages) <= 2:
Wondering the same, this could be a bit more descriptive tbh

2017-10-26 19:52 UTC, Vynny commented on src/backend_service/controllers/conversationController.py
> +        additional_info = {"should_parse_as_html": True}
Instead of additional_info, it'd be better if it returned a 'response_html' rather than 'response_text', that way its a simple if else on the front end

2017-10-26 19:53 UTC, lancelafontaine commented on src/backend_service/controllers/conversationController.py
> +        additional_info = {"should_parse_as_html": True}
Yeah, that makes sense. I'll change that in the next commit.

2017-10-26 19:53 UTC, lancelafontaine commented on src/backend_service/controllers/conversationController.py
> +    if len(conversation.messages) <= 2:
Will make more explicit in next commit.

2017-10-27 00:33 UTC, Vynny requested changes

2017-10-27 00:33 UTC, Vynny commented on src/backend_service/controllers/conversationController.py
> +    if response_text is not None:
This should be response_html

2017-10-27 00:39 UTC, lancelafontaine commented on src/backend_service/controllers/conversationController.py
> +    if response_text is not None:
Fixed in  0bf4305

2017-10-27 00:39 UTC, Vynny approved these changes

2017-10-27 00:50 UTC, dodoels approved these changes

2017-10-27 01:08 UTC, merged